// GENERATED by scripts/build.py - DO NOT EDIT.
// Edit engine/engine_template.js and locales/*.json, then rebuild.
// Antigravity Client Modern Chinese Localization Engine v1.0.0
// Sandboxed Electron compatible with embedded dictionary and real-time DOM translation
// Supports external dictionaries from the Antigravity locales directory:
// the patcher splices them in at injection time, and when the preload has fs
// access (non-sandboxed) they are also hot-reloaded at runtime.

(function() {
    let currentLang = 'zh';
    try {
        currentLang = localStorage.getItem('antigravity_lang') || 'zh';
    } catch (e) {
        console.error('[AG-ZH] Failed to read lang preference:', e);
    }

    // ---------------------------------------------------------------------------
    // Dictionary state: embedded base (spliced in by build.py / patcher) plus
    // optional external overrides from the user-editable locales directory.
    // ---------------------------------------------------------------------------
    const EMBEDDED_TRANSLATIONS = /*AG_ZH_ZH_START*/{
  "Configure the browser subagent. It requires": "配置浏览器子智能体。它需要安装 ",
  "Google Chrome": "Google Chrome",
  "to be installed. The browser subagent can be invoked by typing /browser in the conversation input box.": "。您可以在对话框中输入 /browser 来调用浏览器子智能体。",
  "Choose a predefined security preset for the agent. This controls terminal auto-execution policy, and file access policy.": "为智能体选择预设的安全级别。这将控制终端的自动执行策略以及文件访问策略。",
  "Learn more about": "了解更多关于",
  "Manually customize individual settings.": "手动自定义各项设置。",
  "Default": "默认",
  "Requires manual review for all terminal commands and file accesses outside of the working folders.": "对所有终端命令以及工作文件夹外的文件访问进行人工审查。",
  "Useful for typical development with an emphasis on security. It prioritizes safety over speed by requiring manual approval for all terminal commands and files outside the project directory.": "适用于注重安全性的典型开发场景。它通过要求对所有终端命令以及项目目录之外的文件进行人工批准来优先保证安全性，而非追求执行速度。",
  "Full machine": "完全机器访问",
  "All terminal commands require review. The agent can read or write to any file in the machine.": "所有终端命令均需审查。智能体可以读取或写入机器上的任何文件。",
  "Useful for tasks that require file access across your full machine. The agent has full read and write access to all local files, but all proposed terminal commands require manual review and approval before running.": "适用于需要跨整台机器访问文件的任务。智能体对所有本地文件具有完全的读写权限，但所有提出的终端命令在运行前都需要进行人工审查和批准。",
  "Unrestricted": "无限制",
  "Disables all safety barriers for maximal iteration velocity.": "禁用所有安全限制以获得最大的迭代速度。",
  "A high-risk mode that disables all safety barriers. The agent operates with full system access, auto-executes all terminal commands, and reads or writes to all local files without review prompts.": "一种禁用所有安全屏障的高风险模式。智能体运行于完全系统访问权限下，自动执行所有终端命令，并读取或写入所有本地文件，而无需任何审查提示。",
  "Inherits from": "继承自",
  "global settings": "全局设置",
  ". Local permissions have higher priority.": "。本地权限具有更高的优先级。",
  "The breakdown below shows token usage from customizations like skills, rules, and MCP. If the budget is exceeded, large customizations will be truncated automatically.": "下方图表显示了由技能、规则和 MCP 等自定义配置所占用的 Token 额度。如果超出预算，大型的自定义配置将会被自动截断。",
  "Customization token budget exceeded. Large customizations will be truncated.": "自定义 Token 预算已超限。大型自定义配置将被自动截断。",
  "% of the customization budget is available.": "% 的自定义预算可用。",
  "Configure global allowed and denied resource permissions.": "配置全局允许和拒绝的资源权限。",
  "Actuation Permissions": "操作权限",
  "Browser Actuation Rules": "浏览器操作规则",
  "Configure allowed and denied URLs for browser actuation.": "配置浏览器操作所允许和拒绝的 URL。",
  "Allow/deny agent browser actuation access to specific URLs.": "允许/拒绝智能体对特定 URL 的浏览器操作访问。",
  "Access": "访问权限",
  "Action required": "需要采取操作",
  "Agent Script": "智能体脚本",
  "Agent Settings": "智能体设置",
  "Agent terminated due to error": "智能体因错误而终止",
  "Antigravity Interactive HTML": "Antigravity 交互式 HTML",
  "Baseline model quota reached": "已达到基础模型配额",
  "Browser Actuation Permissions": "浏览器操作权限",
  "Browser Settings": "浏览器设置",
  "Build With Google Plugins": "使用 Google 插件构建",
  "Capture console logs": "捕获控制台日志",
  "Capture screenshot": "捕获屏幕截图",
  "Chat Settings": "对话设置",
  "Click to copy URL": "点击复制 URL",
  "Click to copy full command": "点击复制完整命令",
  "Close split view and go to forked conversation": "关闭拆分视图并转到派生的对话",
  "Code Search": "代码搜索",
  "Commands": "命令",
  "Commands Outside Sandbox": "沙箱外的命令",
  "Configure Branches": "配置分支",
  "Conversation": "对话",
  "Copy full URL to clipboard": "复制完整 URL 到剪贴板",
  "Copy trajectory ID": "复制运行轨迹 ID",
  "Custom Agents": "自定义智能体",
  "Custom View": "自定义视图",
  "Customize Global Skills": "自定义全局技能",
  "Default Customizations": "默认自定义设置",
  "Download Agent State Debug Diagnostics": "下载智能体状态调试诊断信息",
  "Error fetching MCP prompt": "获取 MCP 提示词时出错",
  "Experimental model. Click to provide feedback or opt out.": "实验性模型。点击以提供反馈或选择退出。",
  "Extensions connection warning": "扩展连接警告",
  "First page": "首页",
  "Full Error": "完整错误",
  "Gcert Authentication": "Gcert 身份验证",
  "Getting started with a Project": "开始使用项目",
  "Google Drive": "Google 云端硬盘",
  "Google Tooling": "Google 工具链",
  "Import AI Studio Project": "导入 AI Studio 项目",
  "Installation": "安装",
  "Installed Skills": "已安装技能",
  "Insufficient AI Credits": "AI 积分不足",
  "Invalid Media": "无效媒体",
  "Knowledge": "知识库",
  "Last page": "尾页",
  "Local": "本地",
  "MCP Configuration Error:": "MCP 配置错误:",
  "MCP Servers": "MCP 服务器",
  "Manage Hooks": "管理挂钩 (Hooks)",
  "Mention Page": "提及页面",
  "Model quota reached": "已达到模型配额",
  "New Worktree": "新工作树",
  "Next page": "下一页",
  "Notification Preferences": "通知偏好设置",
  "Open Trajectory Dashboard": "打开运行轨迹仪表盘",
  "Open project settings": "打开项目设置",
  "Options": "选项",
  "Plugin Operation Error:": "插件操作错误:",
  "Previous page": "上一页",
  "Quota": "配额",
  "Recent Files": "最近文件",
  "Refresh skills paths": "刷新技能路径",
  "Remote Control": "远程控制",
  "Reset State": "重置状态",
  "Rules": "规则",
  "Search conversations (by name or Cascade ID)": "搜索对话（按名称或 Cascade ID）",
  "Segment Metrics": "段度量指标",
  "Select Model to Send Message": "选择发送消息的模型",
  "Side Question Instructions": "侧边提问说明",
  "Skills": "技能",
  "Skills Configuration Error:": "技能配置错误:",
  "Stop Subagent": "停止子智能体",
  "Suggestions": "建议",
  "Switch Roles": "切换角色",
  "Trajectory Metrics": "运行轨迹指标",
  "UI Actions": "UI 操作",
  "Update Available": "有可用更新",
  "Verification required": "需要验证",
  "View Page": "视图页面",
  "Workspace Command Access": "工作区命令访问权限",
  "Workspace File Access": "工作区文件访问权限",
  "Workspace Web Access": "工作区网络访问权限",
  "view full search results": "查看完整搜索结果",
  "Agent Behavior": "智能体行为",
  "Danger Zone": "危险区域",
  "Editor Settings": "编辑器设置",
  "File Permissions": "文件权限",
  "Folders": "文件夹",
  "Layout Controls": "布局控制",
  "Local Permissions": "本地权限",
  "MCP Tools": "MCP 工具",
  "Marketplace": "插件市场",
  "Model Credits": "模型积分",
  "Model Quota": "模型配额",
  "Models": "模型",
  "Network Permissions": "网络权限",
  "Provide Feedback": "提供反馈",
  "Recommended": "推荐",
  "Refresh quota and credits data": "刷新配额与积分数据",
  "Selection Actions": "选择操作",
  "Shortcuts": "快捷键",
  "Terminal & Tooling Permissions": "终端和工具权限",
  "Terminal Commands": "终端命令",
  "Best of N Settings": "Best of N 设置",
  "Accent": "强调色",
  "Accept Step": "接受步骤",
  "Actions": "操作",
  "Add Hook Card": "添加挂钩卡片",
  "Agent Auto-Fix Lints": "智能体自动修复 Linter 错误",
  "Agent Host Address": "智能体主机地址",
  "Agent Non-Workspace File Access": "智能体非工作区文件访问",
  "All tools (*)": "所有工具 (*)",
  "Allow List Terminal Commands": "终端命令允许列表",
  "Allow Once": "允许一次",
  "Allow in Conversation": "在对话中允许",
  "Allow once": "允许一次",
  "Alphabetical (A-Z)": "按字母顺序 (A-Z)",
  "Always Allow": "总是允许",
  "Always Ask": "总是询问",
  "Always Proceed": "总是继续",
  "Always run": "总是运行",
  "Archive / Restore": "存档 / 恢复",
  "Archive this conversation": "存档此对话",
  "Artifact Review Policy": "工件审查策略",
  "Ask Agent for Help": "向智能体寻求帮助",
  "Ask every time": "每次都询问",
  "Ask first": "先询问",
  "Auto-Expand Changes Overview": "自动展开更改概览",
  "Auto-Open Edited Files": "自动打开已编辑的文件",
  "Background": "后台",
  "Backoff": "退避",
  "Blocked": "已阻止",
  "Blocked on Your Input": "等待您的输入",
  "Browser CDP Port": "浏览器 CDP 端口",
  "Browser Javascript Execution Policy": "浏览器 Javascript 执行策略",
  "Browser User Profile Path": "浏览器用户配置文件路径",
  "Browser tools (browser_.*)": "浏览器工具 (browser_.*)",
  "Chrome Binary Path": "Chrome 可执行文件路径",
  "CitC Clone": "CitC 克隆",
  "Close Terminal Tab": "关闭终端标签页",
  "Close Workspace": "关闭工作区",
  "Command picker": "命令选择器",
  "Complete verification": "完成验证",
  "Configure": "配置",
  "Confirm Window Reload": "确认窗口重新加载",
  "Console logs": "控制台日志",
  "Copy Content": "复制内容",
  "Copy File Name": "复制文件名",
  "Copy File Path": "复制文件路径",
  "Copy conversation markdown": "复制对话 Markdown",
  "Copy debug info": "复制调试信息",
  "Created At": "创建时间",
  "Date Added": "添加日期",
  "Delete Handler": "删除处理程序",
  "Delete Hook": "删除挂钩",
  "Deny List Terminal Commands": "终端命令黑名单",
  "Dismiss": "忽略",
  "Enable Browser Tools": "启用浏览器工具",
  "Enable Demo Mode (Beta)": "启用演示模式 (Beta)",
  "Enable Overages": "启用超额度使用",
  "Enable Shell Integration": "启用 Shell 集成",
  "Enable Sounds for Agent": "为智能体启用声音提示",
  "Enable Terminal Sandbox": "启用终端沙箱",
  "Enable Workspace API": "启用工作区 API",
  "Errors": "错误",
  "Explain and Fix in Current Conversation": "在当前对话中进行解释并修复",
  "File picker": "文件选择器",
  "Focus Editor": "聚焦编辑器",
  "Friday": "星期五",
  "Generations": "生成内容",
  "Getting scripts...": "正在获取脚本...",
  "Google3": "Google3",
  "Hide Editor": "隐藏编辑器",
  "Highlight After Accept": "采纳后高亮",
  "In Progress": "进行中",
  "Inactive": "未活动",
  "Last Updated": "最后更新时间",
  "Mark as Read": "标记为已读",
  "Mark as Unread": "标记为未读",
  "Media": "媒体",
  "Mention": "提及",
  "Mention Selection": "提及选定内容",
  "Mentions": "提及",
  "Metadata": "元数据",
  "Monday": "星期一",
  "New Agent Script": "新建智能体脚本",
  "New Editor Window": "新建编辑器窗口",
  "New Terminal Tab": "新建终端标签页",
  "No Subtitle": "无副标题",
  "Open Agent on Reload": "重新加载时打开智能体",
  "Open Command Palette": "打开命令面板",
  "Open Commit Graph": "打开提交图",
  "Open Conversation": "打开对话",
  "Open Conversation History": "打开对话历史记录",
  "Open Keyboard Shortcuts": "打开键盘快捷键",
  "Open Launchpad": "打开控制台",
  "Open Preferences": "打开偏好设置",
  "Open Workspace Selector": "打开工作区选择器",
  "Overwrite": "覆盖",
  "Proceed with Plan": "执行计划",
  "Project": "项目",
  "Projects": "项目",
  "Purchase Credits": "购买积分",
  "Read": "读取",
  "Remove": "移除",
  "Review Policy": "审查策略",
  "Run (unsandboxed)": "运行（非沙箱）",
  "Safe Merge": "安全合并",
  "Sandbox Allow Network": "沙箱允许网络访问",
  "Saturday": "星期六",
  "Screen Recording": "屏幕录制",
  "Screenshot": "屏幕截图",
  "See Plans": "查看方案",
  "Select another model": "选择其他模型",
  "Split Terminal": "拆分终端",
  "Standalone": "独立模式",
  "Start Voice Recording": "开始录音",
  "Step Type": "步骤类型",
  "Stop Voice Recording": "停止录音",
  "Stopped": "已停止",
  "Strict Mode": "严格模式",
  "Suggestions in Editor": "编辑器内建议",
  "Sunday": "星期日",
  "Tab Gitignore Access": "Tab 访问 Gitignore 文件",
  "Tab Speed": "Tab 响应速度",
  "Tab to Import": "Tab 自动导入",
  "Tab to Jump": "Tab 快速跳转",
  "Thursday": "星期四",
  "Toggle Editor": "切换编辑器",
  "Toggle Environment Selector": "切换环境选择器",
  "Toggle Fullscreen": "切换全屏",
  "Toggle Project Selector": "切换项目选择器",
  "Toggle Terminal": "切换终端",
  "Tool": "工具",
  "Tuesday": "星期二",
  "Unknown": "未知",
  "Use": "使用",
  "Use theme to be imported with settings": "使用随设置导入的主题",
  "Wednesday": "星期三",
  "Write": "写入",
  "Best of N": "Best of N (多重生成)",
  "File Access Rules": "文件访问规则",
  "Network Access Rules": "网络访问规则",
  "Security Preset": "安全预设",
  "Marketplace Gallery URL": "插件市场展示 URL",
  "Marketplace Item URL": "插件市场单项 URL",
  "Email": "电子邮箱",
  "Marketing Emails": "营销邮件",
  "File Reads": "文件读取",
  "File Writes": "文件写入",
  "Read Files": "读取文件",
  "Write Files": "写入文件",
  "Read URLs": "读取 URL",
  "Execute URLs": "执行 URL",
  "Disable Eager Cloning": "禁用预先克隆",
  "Maximum Active Workspaces": "最大活动工作区数",
  "Maximum Clones Per Workspace": "每个工作区的最大克隆数",
  "Agent always asks for review.": "智能体总是请求审查。",
  "Agent asks for permission before executing commands matched by a deny list entry.": "智能体在执行匹配拒绝列表条目的命令前会请求许可。",
  "Agent auto-executes commands matched by an allow list entry.": "智能体自动执行允许列表中的命令。",
  "Agent never asks for review. This maximizes the autonomy of the Agent, but also has the highest risk of the Agent operating over unsafe or injected Artifact content.": "智能体绝不请求审查。这可以最大化智能体的自主权，但同时智能体在不安全的或被注入的工件 (Artifact) 内容上运行的风险也最高。",
  "Allow Agent to view and edit files outside of the current workspace automatically. Use with caution: this provides the Agent access to additional potentially-relevant information, but also allows the Agent to access credential files, secrets, and other files outside of the workspace that could be targeted in prompt injection attacks or other exploits by malicious actors.": "允许智能体自动查看和编辑当前工作区之外的文件。请谨慎使用：这为智能体提供了获取其他潜在相关信息的能力，但也允许其访问凭据文件、机密信息以及工作区之外的其他文件，这些文件可能会成为恶意行为者进行提示注入攻击或其他漏洞利用的目标。",
  "Allow Tab to view and edit the files in .gitignore. Use with caution if your .gitignore lists files containing credentials, secrets, or other sensitive information.": "允许 Tab 补全查看和编辑 .gitignore 中的文件。如果您的 .gitignore 中包含密钥、敏感信息等文件，请谨慎启用。",
  "Allow/deny agent command execution outside the sandbox.": "允许/拒绝智能体在沙箱外执行命令。",
  "Allow/deny agent read access to specific URLs or domains.": "允许/拒绝智能体对特定 URL 或域名的读取访问权限。",
  "Allow/deny agent read access to specific files or directories.": "允许/拒绝智能体对特定文件或目录的读取访问权限。",
  "Allow/deny agent write access to specific files or directories.": "允许/拒绝智能体对特定文件或目录的写入访问权限。",
  "Allow/deny specific terminal commands.": "允许/拒绝特定的终端命令。",
  "Allows the agent to access files outside of your current workspace.": "允许智能体访问当前工作区之外的文件。",
  "Ask a quick question without interrupting the main conversation.": "快速提问，不中断主对话。",
  "Checks for pending changes before merging.": "在合并前检查未完成的更改。",
  "Clone current workspace into a new independent workspace": "将当前工作区克隆为一个新的独立工作区",
  "Commands the agent can run outside the sandbox.": "智能体可在沙箱外运行的命令。",
  "Configure agent hooks": "配置智能体挂钩 (Hooks)",
  "Configure default behaviors, skills, and MCP servers.": "配置默认行为、技能和 MCP 服务器。",
  "Configure settings for Best of N mode.": "配置 Best of N 模式的设置。",
  "Controls whether the agent can run custom JavaScript to automate complex browser actions.": "控制智能体是否可以运行自定义 JavaScript 来自动执行复杂的浏览器操作。",
  "Custom path for the browser user profile directory. Leave empty for default (~/.gemini/antigravity-browser-profile).": "浏览器用户配置目录的自定义路径。留空使用默认路径 (~/.gemini/antigravity-browser-profile)。",
  "Determines the markup language of the output.": "确定输出的标记语言。",
  "GCP Project ID for enterprise features.": "企业级功能的 GCP 项目 ID。",
  "Highlight newly inserted text after accepting a Tab completion.": "采纳 Tab 补全后高亮显示新插入的文本。",
  "Hook will only trigger if the tool name matches run_command or view_file.": "仅当工具名称匹配 run_command 或 view_file 时，挂钩才会触发。",
  "Hook will only trigger if the tool name matches run_command.": "仅当工具名称匹配 run_command 时，挂钩才会触发。",
  "Hook will only trigger if the tool name starts with browser_.": "仅当工具名称以 browser_ 开头时，挂钩才会触发。",
  "Hook will trigger if any tool is executed.": "如果执行了任何工具，挂钩都将触发。",
  "If non-zero, all user-specified sizes, e.g. in \\rule{500em}{500em}, will be capped to maxSize ems. Otherwise, elements and spaces can be arbitrarily large": "如果非零，所有用户指定的大小（例如在 \\rule{500em}{500em} 中）都将限制在 maxSize em 内。否则，元素和空间可以任意大",
  "Limit the number of macro expansions to the specified number, to prevent e.g. infinite macro loops. If set to Infinity, the macro expander will try to fully expand as in LaTeX.": "限制宏展开的次数为指定数量，以防止无限宏循环等。如果设置为 Infinity，宏展开器将尝试像 LaTeX 中那样完全展开。",
  "Makes \\color behave like LaTeX's 2-argument \\textcolor, instead of LaTeX's one-argument \\color mode change.": "使 \\color 的行为类似于 LaTeX 的双参数 \\textcolor，而不是 LaTeX 的单参数 \\color 模式更改。",
  "Meta-agent for managing conversations": "用于管理对话的元智能体",
  "Open Agent panel on window reload": "窗口重新加载时打开智能体面板",
  "Open files in the background if Agent creates or edits them": "如果智能体创建或编辑了文件，则在后台打开这些文件",
  "Overwrites changes in the target workspace.": "覆盖目标工作区中的更改。",
  "Path to the Chrome/Chromium executable. Leave empty for auto-detection.": "Chrome/Chromium 可执行文件的路径。留空则自动检测。",
  "Paths the agent can modify.": "智能体可以修改的路径。",
  "Paths the agent can read.": "智能体可以读取的路径。",
  "Port number for Chrome DevTools Protocol remote debugging. Leave empty for default (9222).": "Chrome DevTools Protocol 远程调试的端口号。留空使用默认端口 (9222)。",
  "Predict the location of your next edit and navigates you there with a tab keypress.": "预测您下次编辑的位置，并使用 Tab 键将您导航至该处。",
  "Quickly add and update imports with a tab keypress.": "通过按下 Tab 键快速添加和更新导入项。",
  "Render display math flush left.": "将显示数学公式靠左对齐。",
  "Render display math in leqno style (left-justified tags).": "以 leqno 样式（左对齐标签）渲染显示数学公式。",
  "Render math in display mode, which puts the math in display style (so \\int and \\sum are large, for example), and centers the math on the page on its own line.": "在显示模式下渲染数学公式，这会使公式呈显示样式（例如，\\int 和 \\sum 变大），并在页面上另起一行居中显示。",
  "Run in a new worktree": "在新的工作树 (Worktree) 中运行",
  "Run in your current workspace": "在您的当前工作区中运行",
  "Set the speed of tab suggestions": "设置 Tab 补全建议的生成速度",
  "Show suggestions when typing in the editor": "在编辑器中键入时显示补全建议",
  "Team of subagents to do long running work": "用于执行长期运行任务的子智能体团队",
  "Terminal commands the agent can execute.": "智能体可以执行的终端命令。",
  "Toggle if a confirmation is shown when using the \"Reload Window\" button.": "切换在使用“重新加载窗口”按钮时是否显示确认提示。",
  "Trust the input, enabling all HTML features such as \\url.": "信任输入，启用所有 HTML 功能（如 \\url）。",
  "Turn on strict / LaTeX faithfulness mode, which throws an error if the input uses features that are not supported by LaTeX.": "启用严格/LaTeX 忠实度模式，如果输入使用了 LaTeX 不支持的功能，将抛出错误。",
  "URLs the agent can actuate on using the browser.": "智能体可以使用浏览器操作的 URL。",
  "URLs the agent can read or open in the browser.": "智能体在浏览器中可以读取或打开的 URL。",
  "When enabled, \"Explain and Fix\" actions will continue in the current conversation instead of starting a new one.": "启用后，“解释并修复”操作将在当前对话中继续，而不是启动新对话。",
  "When enabled, 'Explain and Fix' actions will continue in the current conversation instead of starting a new one.": "启用后，“解释并修复”操作将在当前对话中继续，而不是启动新对话。",
  "When enabled, Agent can interact with Google Workspace through the API to search and read documents.": "启用后，智能体可以通过 API 与 Google Workspace 进行交互，以搜索和读取文档。",
  "When enabled, Agent can use browser tools to open URLs, read web pages, and interact with browser content. This allows the Agent access to important (and often critical) knowledge and methods of validation, but any browser integration does increase exposure to external malicious parties for security exploits.": "启用后，智能体可以使用浏览器工具打开 URL、阅读网页并与浏览器内容进行交互。这使得智能体能够获得重要（且通常是关键）的知识和验证方法，但任何浏览器集成确实会增加恶意外部人员进行安全漏洞利用的风险。",
  "When enabled, Agent is given awareness of lint errors created by its edits and may fix them without explicit user prompting.": "启用后，智能体将感知其编辑产生的 Linter 错误，并在无需用户明确提示的情况下自动修复。",
  "When enabled, Agent will use IDE's shell integration to detect and report terminal command execution.": "启用后，智能体将使用 IDE 的 Shell 集成来检测并报告终端命令的执行情况。",
  "When enabled, Agent will use IDE's shell integration to detect and report terminal command execution. When disabled, the agent will use its own shell. Restart the application for this to take effect.": "启用后，智能体将使用 IDE 的 Shell 集成来检测并报告终端命令的执行。禁用时，智能体将使用其自身的 Shell。重启应用程序以使该设置生效。",
  "When enabled, Antigravity will play a sound when Agent finishes generating a response.": "启用后，当智能体完成响应生成时，Antigravity 将播放提示音。",
  "When enabled, enforces settings that prevent the agent from autonomously running targeted exploits and requires human review for all agent actions. Visit antigravity.google/docs/strict-mode for details.": "启用后，将强制执行相关设置以防止智能体自主运行有针对性的漏洞利用，并要求对智能体的所有操作进行人工审查。访问 antigravity.google/docs/strict-mode 了解详情。",
  "When enabled, sandboxed commands are allowed to make network requests.": "启用后，沙箱命令将被允许进行 network 请求。",
  "When enabled, terminal commands run with sandbox restrictions.": "启用后，终端命令将在沙箱限制下运行。",
  "When enabled, the Changes Overview toolbar will automatically expand when Agent finishes generating a response.": "启用后，“更改概览”工具栏将在智能体完成响应生成时自动展开。",
  "When enabled, the agent will be able to access its knowledge base to inform its responses and automatically generate knowledge items in the background.": "启用后，智能体将能够访问其知识库以辅助其响应，并在后台自动生成知识项。",
  "When enabled, the agent will be able to access its knowledge base to inform its responses and automatically generate knowledge items in the background. Disabling this will prevent the agent from accessing existing knowledge items, but will not delete them.": "启用后，智能体将能够访问其知识库以辅助响应生成，并自动在后台生成知识项。禁用此功能将阻止智能体访问已有的知识项，但不会删除它们。",
  "When enabled, the agent will be able to access past conversations to inform its responses.": "启用后，智能体将能够访问过去的对话来作为响应生成的参考。",
  "When enabled, your UI will be slightly modified to ensure more consistent demos. This is only recommended for demo purposes. In most cases, you can run \"Antigravity: Start Demo Mode\" and \"Antigravity: Stop Demo Mode\" to control this switch and update your ~/.gemini/antigravity data directory.": "启用后，您的 UI 将会有轻微修改，以确保演示效果的一致性。这仅推荐在演示目的下使用。在大多数情况下，您可以运行“Antigravity: 开始演示模式”和“Antigravity: 停止演示模式”来控制此开关并更新您的 ~/.gemini/antigravity 数据目录。",
  "When running commands, the agent will try to use this address, and fall back to to the \"connector.host.featureDefault\" host if not defined.  Note: hosts set here with auto-run enabled will have internet access restricted soon.": "在运行命令时，智能体将尝试使用此地址，如果未定义，将回退到“connector.host.featureDefault”主机。注意：此处设置了启用自动运行的主机，其互联网访问权限很快将受到限制。",
  "Would you like to grant the agent access to google drive?": "您是否要授予智能体对 Google 云端硬盘 (Google Drive) 的访问权限？",
  "The app will be accessible from the menu bar and will keep running in the background when all windows are closed.": "应用程序可从菜单栏访问，并在关闭所有窗口时继续在后台运行。",
  "Prevent the computer from sleeping while the app is running.": "在应用运行期间防止计算机进入睡眠状态。",
  "Keyboard shortcuts for quick navigation and control.": "用于快速导航和控制的键盘快捷键。",
  "Manage your notification preferences.": "管理您的通知偏好设置。",
  "Manage your plan, credentials, and general preferences.": "管理您的方案、凭据及通用偏好设置。",
  "Permanently delete this project and all of its conversations.": "永久删除此项目及其所有对话。",
  "Configure AI models and view your quota.": "配置 AI 模型并查看您的配额额度。",
  "Configure the agent's visual theme and display preferences.": "配置智能体的视觉主题与显示偏好。",
  "Configure workspace-specific permissions, resources, and customizations.": "配置特定工作区的权限、资源和自定义设置。",
  "Configure allowed commands outside the sandbox.": "配置沙箱外允许执行的命令。",
  "Configure allowed terminal commands.": "配置允许执行的终端命令。",
  "Configure allowed and denied paths for file reads and writes.": "配置允许和拒绝读取及写入的文件路径。",
  "Configure allowed and denied URLs for reading.": "配置允许和拒绝读取的 URL。",
  "Configure editor-specific behaviors and shortcuts.": "配置编辑器专属行为与快捷键。",
  "Configure external tools via Model Context Protocol.": "通过模型上下文协议 (Model Context Protocol, MCP) 配置外部工具。",
  "External tools the agent can call via Model Context Protocol.": "智能体可以通过模型上下文协议 (MCP) 调用的外部工具。",
  "Configures how the agent tries to access files outside of its working folders.": "配置智能体尝试访问其工作文件夹之外的文件时的行为。",
  "Controls whether terminal commands require your approval before running.": "控制终端命令在运行前是否需要您的批准。",
  "Disable pre-warming of workspace clones.": "禁用工作区克隆的预热功能。",
  "Maximum number of concurrent active source workspaces tracked in the clone pools.": "在克隆池中跟踪的并发活动源工作区的最大数量。",
  "Maximum number of pre-warmed workspace clones cached per active source workspace.": "每个活动源工作区缓存的预热工作区克隆的最大数量。",
  "Paths the agent can modify inside this workspace.": "智能体在此工作区中可以修改的文件路径。",
  "Paths the agent can read inside this workspace.": "智能体在此工作区中可以读取的文件路径。",
  "Terminal commands the agent can execute in this workspace.": "智能体在此工作区中可以执行的终端命令。",
  "URLs the agent can actuate on in this workspace.": "智能体在此工作区中可以操作的 URL。",
  "URLs the agent can read or open in this workspace.": "智能体在此工作区中可以读取或打开的 URL。",
  "Restricts agent tools to a secure, isolated local sandbox.": "将智能体工具限制在安全、隔离的本地沙箱中。",
  "Gives the agent permission to create and upload documents to google drive": "允许智能体创建文档并将其上传到 Google 云端硬盘 (Google Drive)",
  "Gives the agent permission to search through google drive. The agent will only see file titles, not file contents": "允许智能体在 Google 云端硬盘 (Google Drive) 中进行搜索。智能体只能看到文件标题，无法看到文件内容",
  "If enabled, you can manage your conversations from the Antigravity website. Please reload the application to apply this setting.": "启用后，您可以在 Antigravity 网站上管理您的对话。请重新加载应用程序以应用此设置。",
  "Manage Google Drive access permissions.": "管理 Google 云端硬盘 (Google Drive) 访问权限。",
  "View your available model quota and AI credits. Model quota refreshes periodically based on your plan. Enable AI Credit Overages to continue using models when your quota is exhausted.": "查看您可用的模型配额和 AI 积分。模型配额会根据您的方案定期刷新。启用 AI 积分超额使用，以便在配额耗尽时继续使用模型。",
  "View your available model quota. Quota refreshes periodically based on your plan.": "查看您可用的模型配额。配额会根据您的方案定期刷新。",
  "(Optional) Tell us more...": "（可选）请告诉我们更多信息...",
  "Absolute path to the Chrome/Chromium executable": "Chrome/Chromium 可执行文件的绝对路径",
  "Corp Password": "企业/公司密码",
  "Cron expression e.g. 0 */6 * * *": "Cron 表达式，例如 0 */6 * * *",
  "Enter URL pattern...": "输入 URL 模式...",
  "Enter a prompt for the agent": "输入智能体的提示词",
  "Enter command (e.g., git, blaze)...": "输入命令（例如 git, blaze）...",
  "Enter directory path...": "输入目录路径...",
  "Enter file or directory path...": "输入文件或目录路径...",
  "Enter task name": "输入任务名称",
  "Enter tool name or server...": "输入工具名称或服务器...",
  "New hook name": "新挂钩名称",
  "Paste auth code": "粘贴授权码",
  "Paste link or custom(gws...)": "粘贴链接或自定义值 (如 gws...)",
  "Please list the steps to reproduce the issue": "请列出重现此问题的步骤",
  "Project name. E.g. Tasks": "项目名称。例如 Tasks",
  "Prompt to execute on schedule...": "按计划执行的提示词...",
  "Search MCP servers by name": "按名称搜索 MCP 服务器",
  "Search across files...": "在文件中搜索...",
  "Search all convos...": "搜索所有对话...",
  "Search by name or Cascade ID...": "按名称或 Cascade ID 搜索...",
  "Search metrics...": "搜索度量指标...",
  "Search projects...": "搜索项目...",
  "Search skills…": "搜索技能...",
  "Search tasks...": "搜索任务...",
  "Search workspaces...": "搜索工作区...",
  "Type to search...": "输入以搜索...",
  "e.g. \"My Custom Gemini Model\"": "例如 \"我的自定义 Gemini 模型\"",
  "e.g. \"gemini-api:/models/gemini-v3-byom\"": "例如 \"gemini-api:/models/gemini-v3-byom\"",
  "e.g. 8192": "例如 8192",
  "e.g., /path/to/file": "例如 /path/to/file",
  "e.g., curl": "例如 curl",
  "e.g., https://example.com": "例如 https://example.com",
  "e.g., npm test": "例如 npm test",
  "https://open-vsx.org/vscode/gallery": "https://open-vsx.org/vscode/gallery",
  "https://open-vsx.org/vscode/item": "https://open-vsx.org/vscode/item",
  "my-agent-script": "my-agent-script",
  "my-gcp-project-id": "my-gcp-project-id",
  "my-project-id": "my-project-id",
  "{\"command\": \"/path/to/script\", \"args\": [\"--flag\"]}": "{\"command\": \"/path/to/script\", \"args\": [\"--flag\"]}",
  "~/.gemini/antigravity-browser-profile": "~/.gemini/antigravity-browser-profile",
  "Your Plan:": "您的方案:",
  "Prevent Sleep": "防止休眠",
  "Keep In Menu Bar": "保留在菜单栏中",
  "Learn more": "了解更多",
  "Terms of Service": "服务条款",
  "By using this app, you agree to its": "使用此应用即表示您同意其",
  "Get More AI Credits": "获取更多 AI 积分",
  "See Activity": "查看活动",
  "Peter Pan": "Peter Pan",
  "All Workspaces": "所有工作区",
  "AS IS": "保持原样",
  "Command:": "命令:",
  "In addition to the custom skills folder, ": "除了自定义技能文件夹，",
  " will search the following paths in order to find skills for the agent.": " 将按顺序搜索以下路径，以寻找智能体的技能。",
  "For google3 workspaces, paths are relative to //depot and begins with google3/": "对于 google3 工作区，路径相对于 //depot 并以 google3/ 开头",
  "Changes the base URL for marketplace search results. You must restart ": "更改插件市场搜索结果的基准 URL。你必须重启 ",
  " to use the new marketplace after changing this value.": " 才能在更改此值后使用新的插件市场。",
  "Changes the base URL on each extension page. You must restart ": "更改每个扩展页面的基准 URL。你必须重启 ",
  "Receive product updates, tips, and promotions from Google ": "通过电子邮件接收来自 Google ",
  " via email.": " 的产品更新、提示和促销信息。",
  "When toggled on, ": "开启后，",
  " collects usage data to help Google enhance performance and features.": " 将收集使用数据，以帮助 Google 提升性能并改进功能。",
  " will use your AI credits to fulfill model requests once you're out of model quota. ": " 将在您的模型配额用尽时使用您的 AI 积分来满足模型请求。",
  " will always use your model quota first before using AI credits.": " 将始终在开始使用 AI 积分之前优先使用您的模型配额。",
  "Sign in to use ": "登录以使用 ",
  " tokens": " 个 Token",
  " comments": " 条评论",
  "IDE Name: ": "IDE 名称: ",
  "Available AI Credits: ": "可用 AI 积分: ",
  "Build with ": "使用 ",
  " Plugins": " 插件构建",
  "Specifies a minimum thickness, in ems, for fraction lines, `\\sqrt` top lines, `{array}` vertical lines, `\\hline`, `\\hdashline`, `\\underline`, `\\overline`, and the borders of `\\fbox`, `\\boxed`, and `\\fcolorbox`.": "指定分数线、`\\sqrt` 顶线、`{array}` 垂直线、`\\hline`、`\\hdashline`、`\\underline`、`\\overline` 以及 `\\fbox`、`\\boxed` 和 `\\fcolorbox` 边框的最小厚度（以 em 为单位）。",
  "Pro": "专业版",
  "Free": "免费版",
  "Standard": "标准版",
  "Beta": "测试版",
  "Enterprise": "企业版",
  "Individual": "个人版",
  "Google Internal": "Google 内部",
  "Not Signed In": "未登录",
  "Enable Telemetry": "启用遥测",
  "Enable Remote Control": "启用远程控制",
  "Your Plan: ": "您的方案: ",
  "Upgrade to Pro": "升级至专业版",
  "Manage Subscription": "管理订阅",
  "Sign Out": "退出登录",
  "Sign In": "登录",
  "Upgrade": "升级",
  "Account": "账户",
  "General": "通用",
  "Project-Specific Settings": "项目特定设置",
  "Modify scoped permissions, folders, and agent settings like Sandbox and Terminal Command Execution.": "修改特定项目范围内的权限、文件夹以及沙箱和终端命令执行等智能体设置。",
  "Go to Projects": "转到项目",
  "Outside of folders file access policy": "工作区文件夹外的文件访问策略",
  "Terminal Command Auto Execution": "终端命令自动执行",
  "Enable Sandbox Mode (Preview)": "启用沙箱模式（预览）",
  "Proceed in Sandbox": "在沙箱中继续",
  "Require Review": "需要审查",
  "Allow": "允许",
  "Deny": "拒绝",
  "Custom": "自定义",
  "Appearance": "外观",
  "Conversations": "对话",
  "Customizations": "自定义配置",
  "Feedback": "提供反馈",
  "Permissions": "权限",
  "Select light, dark, or inherit system settings.": "选择浅色、深色或继承系统设置。",
  "Verbose agent chat": "详细智能体对话",
  "Display and preserve intermediate thinking steps": "显示并保存中间思考步骤",
  "Foreground": "前景色",
  "Light Theme": "浅色主题",
  "Dark Theme": "深色主题",
  "Preset": "预设",
  "Default Light": "默认浅色",
  "Default Dark": "默认深色",
  "No Plugins Available": "没有可用的插件",
  "There are currently no Build with ": "目前没有使用 ",
  " plugins available.": " 插件可供使用。",
  "No plugins available.": "没有可用的插件。",
  "Submit": "提交",
  "Authenticate": "进行身份验证",
  "Sign out": "退出登录",
  "Sign out of this server?": "确定要退出此服务器的登录状态吗？",
  "Delete server": "删除服务器",
  "Click to disable tool": "点击以禁用此工具",
  "Click to enable tool": "点击以启用此工具",
  "MCP Servers Disabled": "MCP 服务器已禁用",
  "Your administrator has disabled MCP servers for this workspace.": "您的管理员已为此工作区禁用 MCP 服务器。",
  "Loading MCP servers...": "正在加载 MCP 服务器...",
  "Open MCP Config": "打开 MCP 配置",
  "Refresh": "刷新",
  "Refreshing...": "正在刷新...",
  "Add MCP": "添加 MCP",
  "No MCP Servers": "没有已安装的 MCP 服务器",
  "You currently don't have any MCP Servers installed.": "您当前未安装任何 MCP 服务器。",
  " Add an MCP server above or add a custom one via the MCP Config.": " 请在上方添加 MCP 服务器，或通过 MCP 配置添加自定义服务器。",
  " Add an MCP server above": " 请在上方添加一个 MCP 服务器",
  "No MCP servers found for ": "未找到匹配 of MCP 服务器：",
  "Search for MCP servers to add to your configuration": "搜索要添加到您的配置中的 MCP 服务器",
  "Clear search": "清除搜索",
  "Dismiss error": "忽略错误",
  "by Google": "Google 官方",
  "Installed": "已安装",
  "Add": "添加",
  "Add Handler": "添加处理程序",
  "Cancel": "取消",
  "Failed to load hooks.json: ": "加载 hooks.json 失败：",
  "Failed to read hooks.json:": "读取 hooks.json 失败：",
  "Configuration saved successfully!": "配置保存成功！",
  "Failed to save hooks.json: ": "保存 hooks.json 失败：",
  "Failed to write hooks.json:": "写入 hooks.json 失败：",
  "Hook with this name already exists": "已存在同名挂钩",
  "Are you sure you want to delete the hook \"": "确定要删除挂钩 \"",
  "\"?": "\" 吗？",
  "Matcher:": "匹配器：",
  "No handlers configured for ": "未配置处理程序：",
  "Add New Handler to ": "添加新处理程序到 ",
  "Timeout:": "超时时间：",
  "Saving...": "正在保存...",
  "Save Configuration": "保存配置",
  "Pre Tool Use": "工具执行前 (Pre Tool Use)",
  "Post Tool Use": "工具执行后 (Post Tool Use)",
  "Pre Invocation": "智能体执行前 (Pre Invocation)",
  "Post Invocation": "智能体执行后 (Post Invocation)",
  "Stop": "智能体终止后 (Stop)",
  "Command is required": "必须填写命令",
  "Are you sure you want to delete this handler?": "确定要删除此处理程序吗？",
  "Please fill in all required fields: ": "请填写所有必填字段：",
  "Failed to save configuration: ": "保存配置失败：",
  "Installing...": "正在安装...",
  "Install": "安装",
  "Include Jetski Default Customizations": "包含默认内置自定义配置",
  "When enabled, the agent will include default customizations, including default skills.": "启用后，智能体将包括默认的自定义设置，包含默认的技能。",
  "Commands the agent can run outside the sandbox in this workspace.": "智能体在此工作区中可以在沙箱外运行的命令。",
  "Show \"Edit\" and \"Chat\" buttons when selecting text in the editor.": "在编辑器中选中文本时显示“编辑”和“对话”按钮。",
  "Specifies Agent's behavior when asking for review on artifacts, which are documents it creates to enable a richer conversation experience.": "指定智能体在请求审查工件（Artifact，即智能体创建的用于提供更丰富对话体验的文档）时的行为。",
  "Attach Antigravity server logs": "附加 Antigravity 服务器日志",
  "Close Tab": "关闭标签页",
  "Command Palette": "命令面板",
  "Conversation picker": "对话选择器",
  "Create Documents": "创建文档",
  "Create Project": "创建新项目",
  "Current": "当前",
  "Daily": "每日",
  "Delete Project": "删除项目",
  "Enable AI Credit Overages": "启用 AI 积分超额使用",
  "File Picker": "文件选择器",
  "Find in Pane": "在面板中查找",
  "Focus Input": "聚焦输入框",
  "Go Back": "后退",
  "Go Forward": "前进",
  "Hourly": "每小时",
  "Maximize": "最大化",
  "Minimize": "最小化",
  "Model": "模型",
  "No Model Selected": "未选择模型",
  "Open Conversation Picker": "打开对话选择器",
  "Open File Search": "打开文件搜索",
  "Open Settings": "打开设置",
  "Other Conversations": "其他对话",
  "Paste": "粘贴",
  "Project picker": "项目选择器",
  "Provide feedback": "提供反馈",
  "Reset Zoom": "重置缩放",
  "Run": "运行",
  "Select Model": "选择模型",
  "Select Next Conversation": "选择下一对话",
  "Select Previous Conversation": "选择上一对话",
  "Send feedback as": "以该身份发送反馈",
  "Show Selection Actions": "显示选中文本操作",
  "Skill Custom Paths": "技能自定义路径",
  "Toggle Auxiliary Pane": "切换辅助面板",
  "Toggle Developer Tools": "切换开发者工具",
  "Toggle Model Selector": "切换模型选择器",
  "Toggle Voice Recording": "切换语音录制",
  "Weekly": "每周",
  "Zoom In": "放大",
  "Zoom Out": "缩小",
  "[AppState]": "[应用状态]",
  "[Dev] GCP Project ID": "[开发] GCP 项目 ID",
  "[ExtensibilityPlugins]": "[可扩展性插件]",
  "[ProjectUpdates]": "[项目更新]",
  "[TrajectorySummaries]": "[轨迹摘要]",
  "here": "此处",
  "run_command": "运行命令 (run_command)",
  "run_command or view_file": "运行命令或查看文件 (run_command / view_file)",
  "Add recent remote workspace": "添加最近的远程工作区",
  "Background Tasks": "后台任务",
  "Context": "上下文",
  "Files Changed": "文件已更改",
  "Installed MCP Servers": "已安装的 MCP 服务器",
  "Project Settings": "项目设置",
  "Toggle Incognito Mode \\u2014 disables knowledge and conversation history": "切换无痕模式 —— 禁用知识库和对话历史记录",
  "Token Usage": "Token 使用量",
  "Fires before a tool step executes.": "工具步骤执行前触发。",
  "Fires after a tool step completes.": "工具步骤执行完成后触发。",
  "Fires before the model is called.": "模型被调用前触发。",
  "Fires after tool calls finish.": "工具调用结束后触发。",
  "Fires when the execution loop terminates.": "执行循环终止时触发。",
  "+ Add Hook": "+ 添加挂钩",
  "Agent Hooks Configuration": "智能体挂钩 (Hooks) 配置",
  "Loading hooks...": "正在加载挂钩...",
  "Handler #": "处理程序 #",
  "Are you sure you want to delete this hook card?": "确定要删除此挂钩卡片吗？",
  "Configure ": "配置 ",
  "Enter the required configuration values to install this MCP server.": "输入所需的配置值以安装此 MCP 服务器。",
  "Add MCP Servers": "添加 MCP 服务器",
  "Allow remote debugging for this browser instance": "允许为此浏览器实例进行远程调试",
  ", open Chrome": "，打开 Chrome",
  "A new workspace will be created for you when you start a conversation": "当您开始对话时，将为您创建一个新的工作区",
  "Accepted": "已接受",
  "Active background color of the command center": "命令中心激活状态的背景颜色",
  "Active border color of the command center": "命令中心激活状态的边框颜色",
  "Active foreground color of the command center": "命令中心激活状态的前景颜色",
  "Add Context": "添加上下文",
  "Add context": "添加上下文",
  "Add Custom Model": "添加自定义模型",
  "Add Model": "添加模型",
  "Agent is analyzing videos": "智能体正在分析视频",
  "Agent State Debug": "智能体状态调试",
  "Agent Stopped": "智能体已停止",
  "all changes to": "对以下内容的所有更改",
  "all changes to the below files": "对以下文件的所有更改",
  "All Files": "所有文件",
  "Background color of the command center": "命令中心的背景颜色",
  "Best of": "Best of",
  "Best of N Models": "Best of N 模型",
  "bold strikethrough": "加粗删除线",
  "bold underline": "加粗下划线",
  "bold underline strikethrough": "加粗下划线删除线",
  "Border color of the command center": "命令中心的边框颜色",
  "Border color of the command center when the window is inactive": "窗口处于非活动状态时命令中心的边框颜色",
  "Browser": "浏览器",
  "Cancel recording": "取消录音",
  "Cannot start best of N mode while the agent is running": "智能体运行时无法启动 Best of N 模式",
  "Check again": "重新检查",
  "Create a new Fig workspace": "创建新的 Fig 工作区",
  "Default Branch": "默认分支",
  "Deprecated use `method` instead": "已弃用，请改用 `method`",
  "Edit Conversation Title": "编辑对话标题",
  "Edit Custom Model": "编辑自定义模型",
  "Edit Model": "编辑模型",
  "Enable": "启用",
  "Enter": "回车",
  "Environment": "环境",
  "Explain and Fix": "解释并修复",
  "Failed to create new workspace": "创建新工作区失败",
  "Failed to export RPC debug buffer": "导出 RPC 调试缓冲区失败",
  "Failed to send": "发送失败",
  "Failed to send message": "发送消息失败",
  "Features": "功能",
  "Foreground color of the command center": "命令中心的前景颜色",
  "Foreground color of the command center when the window is inactive": "窗口处于非活动状态时命令中心的前景颜色",
  "Google Drive Access": "Google 云端硬盘访问权限",
  "italic bold": "斜体加粗",
  "italic bold strikethrough": "斜体加粗删除线",
  "italic bold underline": "斜体加粗下划线",
  "italic bold underline strikethrough": "斜体加粗下划线删除线",
  "italic strikethrough": "斜体删除线",
  "italic underline": "斜体下划线",
  "italic underline strikethrough": "斜体下划线删除线",
  "Launchpad": "启动板",
  "Max Tokens": "最大 Token 数",
  "MCP Error": "MCP 错误",
  "Missing Folder": "缺失的文件夹",
  "Missing Folders": "缺失的文件夹",
  "Model Label": "模型标签",
  "Model URL": "模型 URL",
  "Model URL info": "模型 URL 信息",
  "Navigate to": "导航至",
  "New Conversation": "新建对话",
  "New Fig Workspace": "新建 Fig 工作区",
  "New Project": "新建项目",
  "New Workspace": "新建工作区",
  "No agent client available to start conversation": "无可用智能体客户端来开始对话",
  "No children conversation IDs returned from server": "服务器未返回子对话 ID",
  "No conversation selected": "未选择对话",
  "No model specified for Battle Mode, falling back to use current selected model": "对战模式未指定模型，将回退使用当前选定的模型",
  "No models available": "无可用模型",
  "No Project": "无项目",
  "No projects found": "未找到项目",
  "No results found": "未找到结果",
  "on your cloudtop server": "在您的 Cloudtop 服务器上",
  "Open Editor": "打开编辑器",
  "Previous Workspaces": "以前的工作区",
  "Previous Worktrees": "以前的工作树",
  "Proceed Anyways": "仍然继续",
  "Processing": "处理中",
  "Quick Start": "快速开始",
  "Recent actions": "最近操作",
  "Record Audio": "录制音频",
  "Record voice memo": "录制语音备忘录",
  "Recording": "录音中",
  "Rejected": "已拒绝",
  "Reload Window": "重新加载窗口",
  "Remote Debugging Required": "需要远程调试",
  "Run in a new git worktree": "在新的 Git 工作树中运行",
  "Run in a new jj workspace or Fig share": "在新的 jj 工作区或 Fig 共享中运行",
  "Running": "运行中",
  "Select a model to send message": "选择发送消息的模型",
  "Select branch": "选择分支",
  "Select Default Branch": "选择默认分支",
  "Select Environment": "选择环境",
  "Select Project": "选择项目",
  "Select workspace to send message": "选择发送消息的工作区",
  "Send Feedback": "发送反馈",
  "Send message": "发送消息",
  "Send Queued Message": "发送排队的消息",
  "Something went wrong": "发生错误",
  "Standalone Conversation": "独立对话",
  "Stop Recording": "停止录音",
  "Stop recording": "停止录音",
  "Style for functions": "函数样式",
  "Style for member functions": "成员函数样式",
  "Thinking": "思考中",
  "Tool Calls": "工具调用",
  "underline strikethrough": "下划线删除线",
  "View MCP settings": "查看 MCP 设置",
  "View plans": "查看方案",
  "Waiting": "等待中",
  "Working": "工作中",
  "Workspaces are not available for this project": "此项目不可用工作区",
  "Worktrees are available for Git repositories": "工作树适用于 Git 仓库",
  "Worktrees are not available for this project": "此项目不可用工作树",
  "Yes, and always allow": "是，且总是允许",
  "Agent settings and permissions for conversations outside of projects.": "项目之外对话的智能体设置和权限。",
  "Manage project folders, agent settings, and permissions.": "管理项目文件夹、智能体设置和权限。",
  "No folders added yet.": "尚未添加任何文件夹。",
  "No project selected or project management not available.": "未选择项目，或项目管理功能不可用。",
  "No customizations found for this workspace.": "此工作区未找到自定义项。",
  "Customize": "自定义",
  "customize": "自定义",
  "Disabled": "已禁用",
  "Request Review": "请求审核",
  "Block all browser JavaScript execution.": "阻止所有浏览器 JavaScript 执行。",
  "Prompt for approval before running browser scripts.": "在运行浏览器脚本前提示审批。",
  "Allow full browser script execution without prompting.": "允许完整的浏览器脚本执行而无需提示。",
  "App": "应用",
  "App Settings": "应用设置",
  "App settings": "应用设置",
  "Keep in Menu Bar": "保留在菜单栏中",
  "Prevent sleep": "防止休眠",
  "App settings & notifications": "应用设置与通知",
  "App Settings & Notifications": "应用设置与通知",
  "App settings and notifications": "应用设置与通知",
  "App Settings and Notifications": "应用设置与通知",
  "System Preferences": "系统偏好设置",
  "System preferences": "系统偏好设置",
  "Open System Preferences": "打开系统偏好设置",
  "Open system preferences": "打开系统偏好设置",
  "Open Notification Preferences": "打开通知偏好设置",
  "Open notification preferences": "打开通知偏好设置",
  "App Settings...": "应用设置...",
  "App settings...": "应用设置...",
  "User message": "用户消息",
  "Agent response": "智能体响应",
  "Good response": "好评",
  "Bad response": "差评",
  "Edit project name": "编辑项目名称",
  "No token data available.": "无 Token 数据可用。",
  "Loading workspace customizations...": "正在加载工作区自定义设置...",
  "Google Drive integration not available": "Google 云端硬盘集成不可用",
  "To modify editor settings, open Settings within the editor window.": "若要修改编辑器设置，请在编辑器窗口中打开设置。",
  "Open Editor Settings": "打开编辑器设置",
  "Notification Settings": "通知设置",
  "To modify notification settings, open your operating system's system preferences.": "若要修改通知设置，请打开操作系统的系统设置。",
  "Manage application settings.": "管理应用设置。",
  "Feedback Type": "反馈类型",
  "Bug Report": "缺陷报告",
  "Feature Request": "功能建议",
  "Auth and Billing": "身份验证与计费",
  "General Feedback": "常规反馈",
  "Description": "描述",
  "Please describe the issue in detail. The more actionable your feedback, the quicker our team can address your request. Some helpful information includes:": "请详细描述问题。您的反馈越具可操作性，我们的团队就能越快处理您的请求。一些有帮助的信息包括：",
  "Steps to reproduce the issue": "重现问题的步骤",
  "Expected behavior": "预期行为",
  "Actual behavior": "实际行为",
  "Any error messages": "任何错误信息",
  "Any relevant information": "任何相关信息",
  "Describe the bug you encountered...": "描述您遇到的缺陷...",
  "Steps to Reproduce": "重现步骤",
  "Attach a screenshot (optional)": "附加屏幕截图（可选）",
  "We recommend attaching logs. Attaching logs will help the Antigravity team act on and prioritize your feedback.": "我们建议您附加日志。附加日志将帮助 Antigravity 团队处理您的反馈并排列优先级。",
  "Add scheduled task": "添加计划任务",
  "No scheduled tasks configured.": "未配置计划任务。",
  "Configure Application Theme Settings": "配置应用程序主题设置",
  "Creating Chinese Localization Plugin": "创建中文汉化插件",
  "Translating Conversation Tooltips": "汉化对话悬浮提示",
  "Localizing Menu Items": "汉化菜单项",
  "Create new project": "创建新项目",
  "Create a new project": "创建新项目",
  "Show decisions": "显示决定",
  "Show Decisions": "显示决定",
  "Show decision": "显示决定",
  "Show Decision": "显示决定",
  "Decisions": "决定",
  "Decision": "决定",
  "Show Projects": "显示项目",
  "File": "文件",
  "Edit": "编辑",
  "View": "视图",
  "Window": "窗口",
  "Help": "帮助",
  "New Window": "新建窗口",
  "Close Window": "关闭窗口",
  "Close": "关闭",
  "Exit": "退出",
  "Undo": "撤销",
  "Redo": "重做",
  "Cut": "剪切",
  "Copy": "复制",
  "Paste and Match Style": "粘贴并匹配样式",
  "Paste and match style": "粘贴并匹配样式",
  "Delete": "删除",
  "Select All": "全选",
  "Select all": "全选",
  "Speech": "语音",
  "Start Speaking": "开始朗读",
  "Stop Speaking": "停止朗读",
  "Reload": "重新加载",
  "Force Reload": "强制重新加载",
  "Force reload": "强制重新加载",
  "Toggle DevTools": "切换开发者工具",
  "Toggle developer tools": "切换开发者工具",
  "Actual Size": "实际大小",
  "Reset zoom": "实际大小",
  "Toggle Full Screen": "切换全屏",
  "Zoom": "缩放",
  "Bring All to Front": "前置全部窗口",
  "Bring all to front": "前置全部窗口",
  "Front": "前置",
  "Docs": "文档",
  "Check for Updates": "检查更新",
  "Checking for Updates...": "正在检查更新...",
  "Downloading Update...": "正在下载更新...",
  "Restart to Update": "重启以更新",
  "Learn More": "了解更多",
  "Documentation": "文档",
  "Community Discussion": "社区讨论",
  "Search Issues": "搜索问题",
  "Toggle Spell Checker": "切换拼写检查",
  "Toggle spell checker": "切换拼写检查",
  "Services": "服务",
  "Hide Antigravity": "隐藏 Antigravity",
  "Hide Others": "隐藏其他",
  "Show All": "显示全部",
  "About Antigravity": "关于 Antigravity",
  "About": "关于",
  "Quit Antigravity": "退出 Antigravity",
  "Quit": "退出",
  "Preferences": "偏好设置",
  "Preferences...": "偏好设置...",
  "Settings": "设置",
  "Settings...": "设置...",
  "App Settings & Notifications...": "应用设置与通知...",
  "App settings & notifications...": "应用设置与通知...",
  "App Settings and Notifications...": "应用设置与通知...",
  "App settings and notifications...": "应用设置与通知...",
  "App Settings  Notifications": "应用设置与通知",
  "App Settings  Notifications...": "应用设置与通知...",
  "Toggle Sidebar": "切换侧边栏",
  "Toggle sidebar": "切换侧边栏",
  "toggle sidebar": "切换侧边栏",
  "Conversation History": "对话历史记录",
  "Conversation history": "对话历史记录",
  "conversation history": "对话历史记录",
  "Scheduled Tasks": "计划任务",
  "Scheduled tasks": "计划任务",
  "scheduled tasks": "计划任务",
  "Sidebar": "侧边栏",
  "New conversation": "新建对话",
  "Start first conversation": "开始首次对话",
  "New Conversation in Project": "在项目中新建对话",
  "New Conversation in Workspace": "在工作区中新建对话",
  "Create project from scratch": "从头开始创建项目",
  "Create New Project": "创建新项目",
  "Instantly create a new project and folder to start building.": "立即创建新项目和文件夹以开始构建。",
  "Create a new project. You can add folders to it now or later.": "创建一个新项目。您可以现在或稍后添加文件夹。",
  "Name your project": "命名您的项目",
  "New standalone conversation, outside of projects.": "项目之外的新独立对话。",
  "Select workspace...": "选择工作区...",
  "Create project with existing folder(s).": "使用现有文件夹创建项目。",
  "Work in Google3. Create conversations in new and existing Fig workspaces.": "在 Google3 中工作。在新的和现有的 Fig 工作区中创建对话。",
  "Get started by creating your first project.": "通过创建您的第一个项目来开始。",
  "Create a Project": "创建项目",
  "Welcome to Jetski Projects": "欢迎使用 Jetski 项目",
  "Project Detected": "检测到项目",
  "Creating projects for your conversations": "为您的对话创建项目",
  "Open Project Picker": "打开项目选择器",
  "No project selected": "未选择项目",
  "No conversations available": "无可用对话",
  "Search conversations...": "搜索对话...",
  "No conversations matching your search": "没有匹配您搜索的对话",
  "No conversations match the selected filters": "没有匹配所选筛选条件的对话",
  "Pin Conversation": "置顶对话",
  "Pin conversation": "置顶对话",
  "pin conversation": "置顶对话",
  "Unpin Conversation": "取消置顶对话",
  "Unpin conversation": "取消置顶对话",
  "unpin conversation": "取消置顶对话",
  "Archive Conversation": "归档对话",
  "Archive conversation": "归档对话",
  "archive conversation": "归档对话",
  "Unarchive Conversation": "取消归档对话",
  "Unarchive conversation": "取消归档对话",
  "unarchive conversation": "取消归档对话",
  "Pin": "置顶",
  "Unpin": "取消置顶",
  "Archive": "归档",
  "Unarchive": "取消归档",
  "See less": "收起",
  "See Less": "收起",
  "see less": "收起",
  "Seeless": "收起",
  "seeless": "收起",
  "See more": "展开",
  "See More": "展开",
  "see more": "展开",
  "Seemore": "展开",
  "seemore": "展开",
  "Show less": "显示更少",
  "Show Less": "显示更少",
  "show less": "显示更少",
  "Show more": "显示更多",
  "Show More": "显示更多",
  "show more": "显示更多",
  "Add Folder": "添加文件夹",
  "Add folder": "添加文件夹",
  "add folder": "添加文件夹",
  "Open": "打开",
  "open": "打开",
  "Display Options": "显示选项",
  "Display options": "显示选项",
  "display options": "显示选项",
  "Display Option": "显示选项",
  "display option": "显示选项",
  "Project Display Options": "项目显示选项",
  "Project display options": "项目显示选项",
  "project display options": "项目显示选项",
  "Message input": "消息输入框",
  "message input": "消息输入框",
  "Ask anything, @ to mention, / for actions": "任意提问，输入 @ 提及，/ 执行操作",
  "Typeahead menu": "自动补全菜单",
  "Authenticating...": "正在身份验证...",
  "Settings - Account": "设置 - 账户",
  "Settings-Account": "设置-账户",
  "Settings > Account": "设置 > 账户",
  "Account Settings": "账户设置",
  "Account settings": "账户设置",
  "account settings": "账户设置",
  "Settings - General": "设置 - 通用",
  "Settings-General": "设置-通用",
  "Settings > General": "设置 > 通用",
  "General Settings": "通用设置",
  "General settings": "通用设置",
  "general settings": "通用设置",
  "You can upgrade to receive the highest rate limits.": "您可以升级以获得最高速率限制。",
  "you can upgrade to receive the highest rate limits.": "您可以升级以获得最高速率限制。",
  "Toggle auxiliary pane": "切换辅助面板",
  "toggle auxiliary pane": "切换辅助面板",
  "Toggle Auxiliary Panel": "切换辅助面板",
  "Toggle auxiliary panel": "切换辅助面板",
  "toggle auxiliary panel": "切换辅助面板",
  "Auxiliary Pane": "辅助面板",
  "Auxiliary pane": "辅助面板",
  "auxiliary pane": "辅助面板",
  "Auxiliary Panel": "辅助面板",
  "Auxiliary panel": "辅助面板",
  "auxiliary panel": "辅助面板",
  "Close Auxiliary Pane": "关闭辅助面板",
  "Close auxiliary pane": "关闭辅助面板",
  "close auxiliary pane": "关闭辅助面板",
  "Close Auxiliary Panel": "关闭辅助面板",
  "Close auxiliary panel": "关闭辅助面板",
  "close auxiliary panel": "关闭辅助面板",
  "Subagents": "子智能体",
  "subagents": "子智能体",
  "Artifacts": "工件",
  "artifacts": "工件",
  "Overview": "概览",
  "overview": "概览",
  "Review": "审查",
  "review": "审查",
  "Worktree": "工作树",
  "worktree": "工作树",
  "Tasks": "任务",
  "tasks": "任务",
  "Terminal": "终端",
  "terminal": "终端",
  "Browser Actuation": "浏览器操作",
  "browser actuation": "浏览器操作",
  "Agent Hooks": "智能体挂钩",
  "agent hooks": "智能体挂钩",
  "Move changes to main": "将更改移至 main",
  "move changes to main": "将更改移至 main",
  "Move Changes to Main": "将更改移至 main",
  "Move changes to main branch": "将更改移至 main 分支",
  "move changes to main branch": "将更改移至 main 分支",
  "Move changes to main...": "将更改移至 main...",
  "move changes to main...": "将更改移至 main...",
  "Move Changes to Main...": "将更改移至 main...",
  "Configure agent execution, queued message delivery, and permissions.": "配置智能体执行、排队消息传递及权限。",
  "Execution": "执行",
  "Queued Messages": "排队消息",
  "Configure when follow-up messages are sent.": "配置何时发送跟进消息。",
  "Keyboard shortcuts": "键盘快捷键",
  "Enter Queues after the turn": "Enter：在当前轮次后排队",
  "Alt+Enter Sends immediately": "Alt+Enter：立即发送",
  "Alt+Enter On empty prompt, sends next in queue": "Alt+Enter：输入框为空时，发送队列中的下一条",
  "Cmd+Enter Sends immediately": "Cmd+Enter：立即发送",
  "Cmd+Enter On empty prompt, sends next in queue": "Cmd+Enter：输入框为空时，发送队列中的下一条",
  "Queues after the turn": "在当前轮次后排队",
  "Sends immediately": "立即发送",
  "On empty prompt, sends next in queue": "输入框为空时，发送队列中的下一条",
  "Queue": "排队",
  "Send Immediately": "立即发送",
  "Interrupt the agent and send immediately.": "打断智能体并立即发送。",
  "Queue until after the current turn.": "排队等待直到当前轮次结束。",
  "Controls the actions the agent can take.": "控制智能体可以执行的操作。",
  "Tool Permissions": "工具权限",
  "Modify permissions for file, terminal, and MCP tools.": "修改文件、终端和 MCP 工具的权限。",
  "Whether the agent asks you to review its documents.": "智能体是否要求您审查其文档。",
  "to be installed.": "。",
  "The browser subagent can be invoked by typing /browser in the conversation input box.": "您可以在对话框中输入 /browser 来调用浏览器子智能体。",
  "The browser subagent has been disabled by your administrator. Contact your administrator to enable browser use.": "浏览器子智能体已被您的管理员禁用。请联系您的管理员以启用浏览器。",
  "Browser Subagent Viewer": "浏览器子智能体查看器",
  "Browser Task": "浏览器任务",
  "Let the agent use browser tools to open URLs, read web pages, and interact with browser content. This gives the agent access to important (and often critical) knowledge, documentation, and web apps.": "允许智能体使用浏览器工具打开网址、读取网页并与浏览器内容交互。这使智能体能够访问重要（通常是关键的）知识、文档和 Web 应用。",
  "Application": "应用程序",
  "Manage Antigravity app settings.": "管理 Antigravity 应用程序设置。",
  "Keep the app accessible from the menu bar and running in the background when all windows are closed.": "当所有窗口关闭时，保持应用在菜单栏中可访问并在后台运行。",
  "Work with local agents from another device.": "从其他设备使用本地智能体。",
  "Manage your conversations from the companion website.": "从配套网站管理您的对话。",
  "Nickname": "昵称",
  "A nickname for identifying this application in the companion website. Changing this will restart the connection.": "在配套网站中标识此应用程序的昵称。修改此项将重启连接。",
  "A label for this computer when you connect from another device. Changing it reconnects.": "从其他设备连接时此计算机的标签。修改后将重新连接。",
  "Notifications": "通知",
  "Version": "版本",
  "App version": "应用版本",
  "Advanced Settings": "高级设置",
  "Automatic Check for Updates": "自动检查更新",
  "Automatically prompt you to restart the app when a new update is available. When disabled, you can check for updates manually from the app menu.": "当有新版本可用时自动提示重启应用。禁用后，您可以通过应用菜单手动检查更新。",
  "Verbose Agent Chat": "详细智能体对话",
  "Display and preserve intermediate thinking steps.": "显示并保留中间思考步骤。",
  "Conversation Width": "对话面板宽度",
  "Configure the maximum width of the conversation panel.": "配置对话面板的最大宽度。",
  "Narrow": "较窄",
  "Wide": "较宽",
  "Models & Usage": "模型与用量",
  "Manage your model quota and credits.": "管理您的模型配额与积分。",
  "Plan": "方案",
  "You can upgrade to a Google AI Ultra plan to receive higher rate limits.": "您可以升级至 Google AI Ultra 方案以获取更高的速率限制。",
  "Gemini Models": "Gemini 模型",
  "Models within this group: Gemini Flash, Gemini Pro": "该组包含的模型: Gemini Flash, Gemini Pro",
  "Claude and GPT models": "Claude 与 GPT 模型",
  "Weekly Limit Remaining": "每周剩余额度",
  "Five Hour Limit Remaining": "5小时剩余额度",
  "Available AI Credits:": "可用 AI 积分:",
  "No quota information available.": "暂无配额信息。",
  "A Gemini-powered security agent decides if commands should be auto-approved.": "由 Gemini 驱动的安全智能体决定是否自动批准命令。",
  "Allow sandboxed commands to make network requests.": "允许沙箱命令发起网络请求。",
  "Allow the agent to automatically view and edit files outside the current workspace. Use with caution: this gives the agent access to additional potentially-relevant information, but also allows the agent to access credential files, secrets, and other files outside of the workspace that could be targeted in prompt injection attacks or other exploits by malicious actors.": "允许智能体自动查看和编辑当前工作区之外的文件。请谨慎使用：这使智能体能够获取更多相关信息，但也允许其访问工作区外的凭据文件、机密等可能被恶意利用的敏感文件。",
  "Allow the agent to run without restrictions.": "允许智能体无限制运行。",
  "Every terminal command requires approval.": "每个终端命令都需要审批。",
  "Run terminal commands with sandbox restrictions.": "在沙箱限制下运行终端命令。",
  "The agent auto-executes commands matched by an allow list entry.": "智能体自动执行匹配白名单条目的命令。",
  "The agent asks for permission before executing commands matched by a deny list entry.": "智能体在执行匹配黑名单条目的命令前请求许可。",
  "Command Setup Script": "命令初始化脚本",
  "A shell setup script run before every command the agent executes in this project. Overrides the global script.": "智能体在此项目中执行每个命令前运行的 Shell 初始化脚本。将覆盖全局脚本。",
  "A shell setup script run before every command the agent executes.": "智能体执行每个命令前运行的 Shell 初始化脚本。",
  "Enforce settings that prevent the agent from autonomously running targeted exploits and require human review for all agent actions. Visit antigravity.google/docs/strict-mode for details.": "强制执行防止智能体自主发起攻击的设置，并要求对所有智能体操作进行人工审查。详情请访问 antigravity.google/docs/strict-mode。",
  "Tab": "Tab 补全",
  "Configure tab completion, suggestions, and navigation behavior.": "配置 Tab 补全、代码建议及导航行为。",
  "Predict the location of your next edit and navigate you there with a tab keypress.": "预测下一次编辑的位置，并通过按下 Tab 键直接导航到该处。",
  "Fast": "快速",
  "Slow": "平缓",
  "Include default customizations, such as default skills.": "包含默认自定义配置，例如内置系统技能。",
  "Enable Personal Customizations": "启用个人自定义配置",
  "Layer your personal customizations (skills, rules, etc.) from your config on top of workspace customizations.": "将个人配置（技能、规则等）叠加应用到当前工作区配置之上。",
  "Add MCP Server": "添加 MCP 服务器",
  "Add MCP server": "添加 MCP 服务器",
  "MCP servers": "MCP 服务器",
  "MCP tool": "MCP 工具",
  "Browse and enable plugins from the Build With Google catalog.": "浏览并启用 Build With Google 目录中的插件。",
  "Labs": "实验室",
  "Try out early-stage features before they ship. These may change or be removed at any time.": "体验尚在早期阶段的实验性功能。这些功能随时可能会修改或移除。",
  "Conversation Sharing": "对话共享",
  "Generate a link that lets any Googler load a read-only copy of a conversation. Sharing exports the conversation history to your public x20 folder, so it needs that folder to be readable by others.": "生成一个链接，允许其他人加载此对话的只读副本。共享会将对话历史导出，需要目标具备可读权限。",
  "Inline Actions": "浮动即时操作",
  "Show a floating notification card when background conversations need your input. Answer questions, approve commands, and grant permissions without leaving your current conversation.": "当后台对话需要您的输入时显示浮动通知卡片。无需离开当前对话即可回答问题、批准命令并授予权限。",
  "Manage how Best of N sets up the workspaces its arms run in.": "管理 Best of N 如何为其各分支构建运行工作区。",
  "Use full VCS clones for Best of N": "Best of N 使用完整版本控制克隆",
  "Use full Git clones for Best of N": "Best of N 使用完整 Git 克隆",
  "Give each Best of N fork a full clone of your workspace, including its local commit history. Choosing a winner then gives your workspace that fork's commit history.": "为每个 Best of N 分支提供工作区的完整克隆（包含本地提交历史）。选择获胜方案后会将该分支的提交历史合并至当前工作区。",
  "Give each Best of N fork its own clone of your Git repository instead of a copy-on-write overlay. Each fork is then a real repository, so commits, branches, and merges work normally.": "为每个 Best of N 分支创建独立的 Git 仓库克隆而非写时复制层。每个分支都是真实的独立仓库，因此提交、分支和合并均可正常运行。",
  "Close Settings": "关闭设置",
  "Developer": "开发者",
  "Developer-only tools. These settings are stored locally in this browser and do not affect other users.": "仅供开发者使用的工具。这些设置保存在本地，不会影响其他用户。",
  "Open in Remote Control": "在远程控制中打开",
  "Continue your work from another device with Remote Control. Scan the QR code or open the link below.": "通过远程控制从另一台设备继续您的工作。扫描下方二维码或打开链接。",
  "CitC Settings": "CitC 设置",
  "Manage settings specific to Google CitC workspaces development.": "管理 Google CitC 工作区开发专用的设置。",
  "GitHub Permissions": "GitHub 权限",
  "Manage fine-grained permissions for GitHub.": "管理 GitHub 的细粒度访问权限。",
  "Activity": "活动",
  "Agents": "智能体",
  "Automations": "自动化",
  "Approval": "审批",
  "Archive Workspace": "归档工作区",
  "Archive project": "归档项目",
  "Add Workspace": "添加工作区",
  "Current Workspace": "当前工作区",
  "Current workspace": "当前工作区",
  "Open Workspace": "打开工作区",
  "Workspace Settings": "工作区设置",
  "Branch Changes": "分支更改",
  "Collapse All Folders": "折叠所有文件夹",
  "Expand All Folders": "展开所有文件夹",
  "Changes": "更改",
  "Commit": "提交",
  "Commit succeeded": "提交成功",
  "Failed to Commit": "提交失败",
  "Failed to Push": "推送失败",
  "Delete Conversation": "删除对话",
  "Open in new tab": "在新标签页中打开",
  "Open side-by-side view": "打开并排视图",
  "Equalize Split Panes": "平分拆分窗格",
  "Fit the whole trajectory": "适应整个轨迹",
  "Copy thinking": "复制思考过程",
  "Show more results": "显示更多结果",
  "Streaming Generation": "流式生成",
  "System Prompt": "系统提示词",
  "System Instruction": "系统指令",
  "Terminal: Add to Chat": "终端：添加到对话",
  "Terminals": "终端列表",
  "Theme": "主题",
  "Tokens": "Token",
  "Uptime": "运行时间",
  "Usage": "用量",
  "View Installed": "查看已安装",
  "View child subagents": "查看子智能体",
  "Ask for permission for sensitive operations.": "在执行敏感操作时请求许可。",
  "Automatically expand the Changes Overview toolbar when the agent finishes generating a response.": "当智能体完成响应生成时，自动展开“更改概览”工具栏。",
  "Open files in the background if the agent creates or edits them": "如果智能体创建或编辑了文件，则在后台自动打开这些文件",
  "Play a sound when the agent finishes generating a response.": "当智能体完成响应生成时播放提示音。",
  "Show browser notifications when your action is needed or execution finishes.": "当需要您采取操作或执行完成时显示通知。",
  "Give the agent awareness of lint errors created by its edits so it can fix them without explicit prompting.": "让智能体感知其编辑引发的 Lint 错误，以便无需显式提示即可自动修复。",
  "Let the agent access its knowledge base to inform its responses and automatically generate knowledge items in the background. Turning this off prevents the agent from accessing existing knowledge items, but doesn't delete them.": "允许智能体访问其知识库以辅助生成回答，并在后台自动生成知识项。关闭此项将阻止智能体访问现有知识项，但不会删除它们。",
  "Let the agent access past conversations to inform its responses.": "允许智能体访问过去的对话历史以辅助生成回答。",
  "Use the IDE's shell integration to detect and report terminal command execution. When disabled, the agent uses its own shell. Restart the application for this to take effect.": "使用 IDE 的 Shell 集成来检测并报告终端命令执行情况。禁用后，智能体将使用独立的 Shell。重启应用后生效。",
  "Allow read access to this path?": "允许对此路径的读取访问？",
  "Allow write access to this path?": "允许对此路径的写入访问？",
  "Allow reading this URL?": "允许读取此 URL？",
  "Allow executing actions on this URL?": "允许在此 URL 上执行操作？",
  "Allow running this command?": "允许运行此命令？",
  "Allow running this command outside the sandbox?": "允许在沙箱外部运行此命令？",
  "Allow using this MCP tool?": "允许使用此 MCP 工具？",
  "Allow access to this resource?": "允许访问此资源？",
  "Save rule to always allow read access to this path?": "保存规则以总是允许读取此路径？",
  "Save rule to always allow write access to this path?": "保存规则以总是允许写入此路径？",
  "Save rule to always allow reading this URL?": "保存规则以总是允许读取此 URL？",
  "Save rule to always allow executing actions on this URL?": "保存规则以总是允许在此 URL 上执行操作？",
  "Save rule to always allow running this command?": "保存规则以总是允许运行此命令？",
  "Save rule to always allow running this command outside the sandbox?": "保存规则以总是允许在沙箱外部运行此命令？",
  "Save rule to always allow using this MCP tool?": "保存规则以总是允许使用此 MCP 工具？",
  "Save rule to always allow access to this resource?": "保存规则以总是允许访问此资源？",
  "允许 read access to this path?": "允许对此路径的读取访问？",
  "read access to this path": "对此路径的读取访问",
  "read access to this path?": "对此路径的读取访问？",
  "write access to this path": "对此路径的写入访问",
  "write access to this path?": "对此路径的写入访问？",
  "reading this URL": "读取此 URL",
  "reading this URL?": "读取此 URL？",
  "executing actions on this URL": "在此 URL 上执行操作",
  "executing actions on this URL?": "在此 URL 上执行操作？",
  "running this command": "运行此命令",
  "running this command?": "运行此命令？",
  "running this command outside the sandbox": "在沙箱外部运行此命令",
  "running this command outside the sandbox?": "在沙箱外部运行此命令？",
  "using this MCP tool": "使用此 MCP 工具",
  "using this MCP tool?": "使用此 MCP 工具？",
  "access to this resource": "访问此资源",
  "access to this resource?": "访问此资源？",
  "Yes, allow this time": "是，仅允许本次",
  "Yes, and always allow in this conversation": "是，且在当前对话中总是允许",
  "Yes, and always allow when not in a project": "是，且在非项目内时总是允许",
  "Yes, and always allow in this project": "是，且在此项目中总是允许",
  "Yes, and always allow in this workspace": "是，且在此工作区中总是允许",
  "Yes, and always allow globally": "是，且全局总是允许",
  "Yes, save rule in this conversation": "是，在此对话中保存规则",
  "Yes, save rule when not in a project": "是，在非项目内时保存规则",
  "Yes, save rule in this project": "是，在此项目中保存规则",
  "Yes, save rule in this workspace": "是，在此工作区中保存规则",
  "Yes, save rule globally": "是，全局保存规则",
  "No": "否",
  "Yes": "是",
  "(tell the agent what to do instead)": "（告知智能体改做什么）",
  "tell the agent what to do instead": "告知智能体改做什么",
  "No (tell the agent what to do instead)": "否（告知智能体改做什么）",
  "Other (write your answer)": "其他（填写您的回答）",
  "Something else (optional)": "其他内容（可选）",
  "Edit permission target": "编辑权限目标",
  "Confirm the command is safe to run outside of the sandbox with full network and disk access.": "确认该命令在沙箱外部运行是安全的（拥有完整的网络和磁盘访问权限）。",
  "Requires manual confirmation.": "需要手动确认。",
  "Requires manual confirmation": "需要手动确认",
  "Requesting your permission in Terminal:": "正在请求您在终端中的权限:",
  "Requesting your permission to execute JavaScript:": "正在请求执行 JavaScript 的权限:",
  "Requesting your permission to open URL:": "正在请求打开 URL 的权限:",
  "The agent has questions for you:": "智能体有若干问题需要向您确认:",
  "The agent has a question for you:": "智能体有问题需要向您确认:",
  "Click to respond to the questions.": "点击以回答这些问题。",
  "Click to respond to the question.": "点击以回答该问题。",
  "Action requires your attention": "操作需要您的关注",
  "The agent is waiting for your input.": "智能体正在等待您的输入。",
  "Multi-select": "多选",
  "Previous question": "上一题",
  "Next question": "下一题",
  "Submit (Enter)": "提交 (Enter)",
  "Continue": "继续",
  "Continue (Enter)": "继续 (Enter)",
  "Skip": "跳过",
  "Skip (esc)": "跳过 (Esc)",
  "Skip All": "全部跳过",
  "Why did you choose this response?": "您为什么选择这个回复？",
  "Better instruction following": "更好地遵循了指令",
  "Better solution & code": "更好的解决方案与代码",
  "More thorough research": "更彻底的研究分析",
  "The other model hallucinated": "另一个模型产生了幻觉",
  "Clearer writing & artifacts": "更清晰的表述与产物",
  "Faster response": "响应速度更快"
}/*AG_ZH_ZH_END*/;
    const EMBEDDED_PATTERNS = /*AG_ZH_PATTERNS_START*/[
  {
    "pattern": "^You have used some of your weekly limit, it will fully refresh in (\\d+) days?\\.$",
    "flags": "i",
    "replacement": "您已使用部分每周额度，将在 $1 天后完全刷新。"
  },
  {
    "pattern": "^You have used some of your weekly limit, it will fully refresh in (\\d+) hours?\\.$",
    "flags": "i",
    "replacement": "您已使用部分每周额度，将在 $1 小时后完全刷新。"
  },
  {
    "pattern": "^You have used some of your 5-hour limit, it will fully refresh in (\\d+) hours?\\.$",
    "flags": "i",
    "replacement": "您已使用部分5小时额度，将在 $1 小时后完全刷新。"
  },
  {
    "pattern": "^You have used some of your 5-hour limit, it will fully refresh in (\\d+) seconds?\\.$",
    "flags": "i",
    "replacement": "您已使用部分5小时额度，将在 $1 秒后完全刷新。"
  },
  {
    "pattern": "^Refreshes in (\\d+) days?, (\\d+) hours?$",
    "flags": "i",
    "replacement": "$1 天 $2 小时后刷新"
  },
  {
    "pattern": "^Refreshes in (\\d+) days?$",
    "flags": "i",
    "replacement": "$1 天后刷新"
  },
  {
    "pattern": "^Refreshes in (\\d+) minutes?, (\\d+) seconds?$",
    "flags": "i",
    "replacement": "$1 分钟 $2 秒后刷新"
  },
  {
    "pattern": "^Refreshes in (\\d+) seconds?$",
    "flags": "i",
    "replacement": "$1 秒后刷新"
  },
  {
    "pattern": "^You have used some of your weekly limit, it will fully refresh in (\\d+) days?, (\\d+) hours?\\.$",
    "flags": "i",
    "replacement": "您已使用部分每周额度，将在 $1 天 $2 小时后完全刷新。"
  },
  {
    "pattern": "^You have used some of your weekly limit, it will fully refresh in (\\d+) hours?, (\\d+) minutes?\\.$",
    "flags": "i",
    "replacement": "您已使用部分每周额度，将在 $1 小时 $2 分钟后完全刷新。"
  },
  {
    "pattern": "^You have used some of your 5-hour limit, it will fully refresh in (\\d+) hours?, (\\d+) minutes?\\.$",
    "flags": "i",
    "replacement": "您已使用部分5小时额度，将在 $1 小时 $2 分钟后完全刷新。"
  },
  {
    "pattern": "^You have used some of your 5-hour limit, it will fully refresh in (\\d+) minutes?\\.$",
    "flags": "i",
    "replacement": "您已使用部分5小时额度，将在 $1 分钟后完全刷新。"
  },
  {
    "pattern": "^You have used some of your (.+?) limit, it will fully refresh in (.+?)\\.$",
    "flags": "i",
    "replacement": "您已使用部分 $1 额度，将在 $2 后完全刷新。"
  },
  {
    "pattern": "^Your Plan:\\s*(.+)$",
    "flags": "i",
    "replacement": "您的方案: $1"
  },
  {
    "pattern": "^App version\\s+(\\d+\\..+)$",
    "flags": "i",
    "replacement": "应用版本 $1"
  },
  {
    "pattern": "^now$",
    "flags": "i",
    "replacement": "刚刚"
  },
  {
    "pattern": "^(\\d+)m$",
    "flags": "i",
    "replacement": "$1分钟前"
  },
  {
    "pattern": "^(\\d+)h$",
    "flags": "i",
    "replacement": "$1小时前"
  },
  {
    "pattern": "^(\\d+)d$",
    "flags": "i",
    "replacement": "$1天前"
  },
  {
    "pattern": "^Worked for\\s+(\\d+(?:\\.\\d+)?)\\s*s$",
    "flags": "i",
    "replacement": "工作了 $1 秒"
  },
  {
    "pattern": "^Worked for\\s+(\\d+(?:\\.\\d+)?)\\s*m$",
    "flags": "i",
    "replacement": "工作了 $1 分钟"
  },
  {
    "pattern": "^Worked for\\s+(\\d+(?:\\.\\d+)?)\\s*h$",
    "flags": "i",
    "replacement": "工作了 $1 小时"
  },
  {
    "pattern": "^Thought for\\s+(\\d+(?:\\.\\d+)?)\\s*s$",
    "flags": "i",
    "replacement": "思考了 $1 秒"
  },
  {
    "pattern": "^Thought for\\s+(\\d+(?:\\.\\d+)?)\\s*m$",
    "flags": "i",
    "replacement": "思考了 $1 分钟"
  },
  {
    "pattern": "^Thought for\\s+(\\d+(?:\\.\\d+)?)\\s*h$",
    "flags": "i",
    "replacement": "思考了 $1 小时"
  },
  {
    "pattern": "^Worked for\\s+(\\d+(?:\\.\\d+)?)\\s*seconds?$",
    "flags": "i",
    "replacement": "工作了 $1 秒"
  },
  {
    "pattern": "^Thought for\\s+(\\d+(?:\\.\\d+)?)\\s*seconds?$",
    "flags": "i",
    "replacement": "思考了 $1 秒"
  },
  {
    "pattern": "^Worked for\\s+(\\d+(?:\\.\\d+)?)\\s*minutes?$",
    "flags": "i",
    "replacement": "工作了 $1 分钟"
  },
  {
    "pattern": "^Thought for\\s+(\\d+(?:\\.\\d+)?)\\s*minutes?$",
    "flags": "i",
    "replacement": "思考了 $1 分钟"
  },
  {
    "pattern": "^Worked for\\s+(\\d+(?:\\.\\d+)?)\\s*hours?$",
    "flags": "i",
    "replacement": "工作了 $1 小时"
  },
  {
    "pattern": "^Thought for\\s+(\\d+(?:\\.\\d+)?)\\s*hours?$",
    "flags": "i",
    "replacement": "思考了 $1 小时"
  },
  {
    "pattern": "^(\\d+)\\s+files?\\s+changed$",
    "flags": "i",
    "replacement": "$1 个文件已更改"
  },
  {
    "pattern": "^(\\d+)\\s+files?\\s+created$",
    "flags": "i",
    "replacement": "$1 个文件已创建"
  },
  {
    "pattern": "^(\\d+)\\s+files?\\s+deleted$",
    "flags": "i",
    "replacement": "$1 个文件已删除"
  },
  {
    "pattern": "^(\\d+)\\s+files?\\s+edited$",
    "flags": "i",
    "replacement": "$1 个文件已编辑"
  },
  {
    "pattern": "^(\\d+)\\s+files?\\s+modified$",
    "flags": "i",
    "replacement": "$1 个文件已修改"
  },
  {
    "pattern": "^(\\d+)\\s+files?\\s+read$",
    "flags": "i",
    "replacement": "$1 个文件已读取"
  },
  {
    "pattern": "^(\\d+)\\s+errors?$",
    "flags": "i",
    "replacement": "$1 个错误"
  },
  {
    "pattern": "^(\\d+)\\s+warnings?$",
    "flags": "i",
    "replacement": "$1 个警告"
  },
  {
    "pattern": "^(\\d+)\\s+results?$",
    "flags": "i",
    "replacement": "$1 个结果"
  },
  {
    "pattern": "^(\\d+)\\s+agents?\\s+running$",
    "flags": "i",
    "replacement": "$1 个智能体正在运行"
  },
  {
    "pattern": "^(\\d+)\\s+tasks?\\s+running$",
    "flags": "i",
    "replacement": "$1 个任务正在运行"
  },
  {
    "pattern": "^(\\d+)\\s+items?$",
    "flags": "i",
    "replacement": "$1 个项目"
  },
  {
    "pattern": "^(\\d+)\\s+conversations?$",
    "flags": "i",
    "replacement": "$1 个对话"
  },
  {
    "pattern": "^(\\d+)\\s+changes?$",
    "flags": "i",
    "replacement": "$1 个更改"
  },
  {
    "pattern": "^(\\d+)\\s+lines?\\s+changed$",
    "flags": "i",
    "replacement": "$1 行已更改"
  },
  {
    "pattern": "^(\\d+)\\s+lines?$",
    "flags": "i",
    "replacement": "$1 行"
  },
  {
    "pattern": "^Ran\\s+(\\d+)\\s+commands?$",
    "flags": "i",
    "replacement": "运行了 $1 个命令"
  },
  {
    "pattern": "^Explored\\s+(\\d+)\\s+files?$",
    "flags": "i",
    "replacement": "探索了 $1 个文件"
  },
  {
    "pattern": "^Read\\s+(\\d+)\\s+files?$",
    "flags": "i",
    "replacement": "读取了 $1 个文件"
  },
  {
    "pattern": "^Edited\\s+(\\d+)\\s+files?$",
    "flags": "i",
    "replacement": "编辑了 $1 个文件"
  },
  {
    "pattern": "^Created\\s+(\\d+)\\s+files?$",
    "flags": "i",
    "replacement": "创建了 $1 个文件"
  },
  {
    "pattern": "^Deleted\\s+(\\d+)\\s+files?$",
    "flags": "i",
    "replacement": "删除了 $1 个文件"
  },
  {
    "pattern": "^Version\\s+(.+)$",
    "flags": "i",
    "replacement": "版本 $1"
  },
  {
    "pattern": "^v(\\d+\\.\\d+\\.\\d+.*)$",
    "flags": "i",
    "replacement": "v$1"
  },
  {
    "pattern": "^See all \\((\\d+)\\)$",
    "flags": "i",
    "replacement": "查看全部 ($1)"
  },
  {
    "pattern": "^(\\d+) tasks? running$",
    "flags": "i",
    "replacement": "$1 个任务运行中"
  },
  {
    "pattern": "^Select model, current: (.+)$",
    "flags": "i",
    "replacement": "选择模型，当前：$1"
  },
  {
    "pattern": "^Send feedback as (.+)$",
    "flags": "i",
    "replacement": "以 $1 身份发送反馈"
  },
  {
    "pattern": "^Cancel \\((.+)\\)$",
    "flags": "i",
    "replacement": "取消 ($1)"
  },
  {
    "pattern": "^Refreshes in (\\d+) hours?, (\\d+) minutes?$",
    "flags": "i",
    "replacement": "$1 小时 $2 分钟后刷新"
  },
  {
    "pattern": "^Refreshes in (\\d+) minutes?$",
    "flags": "i",
    "replacement": "$1 分钟后刷新"
  },
  {
    "pattern": "^Individual quota reached\\. .+$",
    "flags": "i",
    "replacement": "个人配额已用完。请联系管理员启用超额。"
  },
  {
    "pattern": "^Files Changed(\\d+)$",
    "flags": "i",
    "replacement": "文件已更改$1"
  },
  {
    "pattern": "^Background Tasks(\\d+)$",
    "flags": "i",
    "replacement": "后台任务$1"
  },
  {
    "pattern": "^Subagents(\\d+)$",
    "flags": "i",
    "replacement": "子智能体$1"
  },
  {
    "pattern": "^Account\\s*[-/>]\\s*Settings$",
    "flags": "i",
    "replacement": "账户设置"
  },
  {
    "pattern": "^Sign in to use\\s+(.+?)!$",
    "flags": "i",
    "replacement": "登录以使用 $1！"
  },
  {
    "pattern": "^When toggled on,\\s+(.+?)\\s+collects usage data to help Google enhance performance and features\\.$",
    "flags": "i",
    "replacement": "开启后，$1 将收集使用数据，以帮助 Google 提升性能并改进功能。"
  },
  {
    "pattern": "^Receive product updates,\\s*tips,\\s*and promotions from Google\\s+(.+?)\\s+via email\\.$",
    "flags": "i",
    "replacement": "通过电子邮件接收来自 Google $1 的产品更新、提示和促销信息。"
  },
  {
    "pattern": "^When toggled on,\\s+(.+?)\\s+will use your AI credits to fulfill model requests once you're out of model quota\\. (.+?) will always use your model quota first before using AI credits\\.$",
    "flags": "i",
    "replacement": "开启后，当您的模型配额用尽时，$1 将使用您的 AI 积分来满足模型请求。$2 将始终在开始使用 AI 积分之前优先使用您的模型配额。"
  },
  {
    "pattern": "^Available AI Credits:\\s*(.+)$",
    "flags": "i",
    "replacement": "可用 AI 积分: $1"
  },
  {
    "pattern": "^Changes the base URL for marketplace search results\\. You must restart (.+?) to use the new marketplace after changing this value\\.$",
    "flags": "i",
    "replacement": "更改插件市场搜索结果的基准 URL。更改此值后，您必须重启 $1 才能使用新的插件市场。"
  },
  {
    "pattern": "^Changes the base URL on each extension page\\. You must restart (.+?) to use the new marketplace after changing this value\\.$",
    "flags": "i",
    "replacement": "更改每个扩展页面的基准 URL。更改此值后，您必须重启 $1 才能使用新的插件市场。"
  },
  {
    "pattern": "^Sign in to use (.+?)!$",
    "flags": "i",
    "replacement": "登录以使用 $1！"
  },
  {
    "pattern": "^(\\d+(?:\\.\\d+)?)%\\s+of the customization budget is available\\.$",
    "flags": "i",
    "replacement": "可用自定义预算：$1%"
  },
  {
    "pattern": "^Active (\\d+)\\s+workspaces?$",
    "flags": "i",
    "replacement": "活动工作区 ($1)"
  },
  {
    "pattern": "^Other (\\d+)\\s+workspaces?$",
    "flags": "i",
    "replacement": "其他工作区 ($1)"
  },
  {
    "pattern": "^Error:\\s+(.+)$",
    "flags": "i",
    "replacement": "错误：$1"
  },
  {
    "pattern": "^Build with (.+?) Plugins$",
    "flags": "i",
    "replacement": "使用 $1 插件构建"
  },
  {
    "pattern": "^Go to Request\\s+#(\\d+)$",
    "flags": "i",
    "replacement": "转到请求 #$1"
  },
  {
    "pattern": "^Go to Step\\s+#(\\d+) and scroll to it$",
    "flags": "i",
    "replacement": "转到步骤 #$1 并滚动到该处"
  },
  {
    "pattern": "^Navigate to step\\s+(\\d+)$",
    "flags": "i",
    "replacement": "导航至步骤 $1"
  },
  {
    "pattern": "^\\[FileWatch:(.+?)\\]$",
    "flags": "i",
    "replacement": "[文件监视:$1]"
  },
  {
    "pattern": "^\\[SidecarLogs-(.+?)\\]$",
    "flags": "i",
    "replacement": "[Sidecar 日志-$1]"
  },
  {
    "pattern": "^Are you sure you want to delete the hook \"(.+?)\"\\?$",
    "flags": "i",
    "replacement": "确定要删除挂钩 \"$1\" 吗？"
  },
  {
    "pattern": "^Please fill in all required fields:\\s*(.+)$",
    "flags": "i",
    "replacement": "请填写所有必填字段：$1"
  },
  {
    "pattern": "^Settings\\s*[-/>]\\s*(.+)$",
    "flags": "i",
    "replacement": "设置 - $1"
  },
  {
    "pattern": "^For\\s+(.+?),\\s+this setting is disabled\\.\\s+This means\\s+(.+?)\\s+does not collect any of your data\\.",
    "flags": "i",
    "replacement": "对于 $1，该设置已被禁用。这意味着 $2 不会收集您的任何数据。"
  },
  {
    "pattern": "^For\\s+(.+?),\\s+this setting is disabled\\.$",
    "flags": "i",
    "replacement": "对于 $1，该设置已被禁用。"
  },
  {
    "pattern": "^Allow read access to (.+)\\?$",
    "flags": "i",
    "replacement": "允许读取 $1？"
  },
  {
    "pattern": "^Allow write access to (.+)\\?$",
    "flags": "i",
    "replacement": "允许写入 $1？"
  },
  {
    "pattern": "^Allow running command (.+)\\?$",
    "flags": "i",
    "replacement": "允许运行命令 $1？"
  },
  {
    "pattern": "^Allow running (.+)\\?$",
    "flags": "i",
    "replacement": "允许运行 $1？"
  },
  {
    "pattern": "^Save rule to always allow (.+)\\?$",
    "flags": "i",
    "replacement": "保存规则以总是允许 $1？"
  },
  {
    "pattern": "^Yes, and always allow '(.+)' in this conversation$",
    "flags": "i",
    "replacement": "是，且在当前对话中总是允许 '$1'"
  },
  {
    "pattern": "^Yes, and always allow '(.+)' when not in a project$",
    "flags": "i",
    "replacement": "是，且在非项目内时总是允许 '$1'"
  },
  {
    "pattern": "^Yes, and always allow '(.+)' in this project$",
    "flags": "i",
    "replacement": "是，且在此项目中总是允许 '$1'"
  },
  {
    "pattern": "^Yes, and always allow '(.+)' in this workspace$",
    "flags": "i",
    "replacement": "是，且在此工作区中总是允许 '$1'"
  },
  {
    "pattern": "^Yes, and always allow '(.+)'$",
    "flags": "i",
    "replacement": "是，且总是允许 '$1'"
  },
  {
    "pattern": "^Yes, save rule for '(.+)' in this conversation$",
    "flags": "i",
    "replacement": "是，在此对话中为 '$1' 保存规则"
  },
  {
    "pattern": "^Yes, save rule for '(.+)' when not in a project$",
    "flags": "i",
    "replacement": "是，在非项目内时为 '$1' 保存规则"
  },
  {
    "pattern": "^Yes, save rule for '(.+)' in this project$",
    "flags": "i",
    "replacement": "是，在此项目中为 '$1' 保存规则"
  },
  {
    "pattern": "^Yes, save rule for '(.+)' in this workspace$",
    "flags": "i",
    "replacement": "是，在此工作区中为 '$1' 保存规则"
  },
  {
    "pattern": "^Yes, save rule for '(.+)' globally$",
    "flags": "i",
    "replacement": "是，全局为 '$1' 保存规则"
  },
  {
    "pattern": "^Requires manual confirmation:\\s*(.+)$",
    "flags": "i",
    "replacement": "需要手动确认: $1"
  },
  {
    "pattern": "^Conflicts with your configured Ask permission:\\s*(.+)$",
    "flags": "i",
    "replacement": "与您配置的询问权限冲突: $1"
  },
  {
    "pattern": "^Requesting permission to (.+)$",
    "flags": "i",
    "replacement": "正在请求 $1 的权限"
  },
  {
    "pattern": "^Skip \\(esc\\), Skip All \\((.+)\\)$",
    "flags": "i",
    "replacement": "跳过 (Esc)，全部跳过 ($1)"
  },
  {
    "pattern": "^Models within this group:\\s*(.+)$",
    "flags": "i",
    "replacement": "该组包含的模型: $1"
  },
  {
    "pattern": "^(Alt\\+Enter|Cmd\\+Enter|Ctrl\\+Enter|Option\\+Enter)\\s+Sends immediately$",
    "flags": "i",
    "replacement": "$1：立即发送"
  },
  {
    "pattern": "^(Alt\\+Enter|Cmd\\+Enter|Ctrl\\+Enter|Option\\+Enter)\\s+On empty prompt, sends next in queue$",
    "flags": "i",
    "replacement": "$1：输入框为空时，发送队列中的下一条"
  },
  {
    "pattern": "^Enter\\s+Queues after the turn$",
    "flags": "i",
    "replacement": "Enter：在当前轮次后排队"
  },
  {
    "pattern": "^Select\\s+(.+?)\\.\\.\\.$",
    "flags": "i",
    "replacement": "选择 $1..."
  },
  {
    "pattern": "^IDE Name:\\s*(.+)$",
    "flags": "i",
    "replacement": "IDE 名称: $1"
  },
  {
    "pattern": "^(\\d+)\\s+comments?$",
    "flags": "i",
    "replacement": "$1 条评论"
  },
  {
    "pattern": "^(.+?):\\s*([\\d,]+)\\s+tokens?$",
    "flags": "i",
    "replacement": "$1: $2 个 Token"
  }
]/*AG_ZH_PATTERNS_END*/;

    let translations = EMBEDDED_TRANSLATIONS;
    let rawPatterns = EMBEDDED_PATTERNS;
    let lowerTranslations = {};
    let patterns = [];

    function rebuildIndexes() {
        lowerTranslations = {};
        for (const key in translations) {
            lowerTranslations[key.toLowerCase()] = translations[key];
        }
        patterns = rawPatterns.map(p => ({
            regex: new RegExp(p.pattern, p.flags || 'i'),
            replace: p.replacement
        }));
    }
    rebuildIndexes();

    // ---------------------------------------------------------------------------
    // External dictionary hot loading. Only works in non-sandboxed preloads;
    // sandboxed ones silently fall back to the embedded dictionary (which the
    // patcher already merged with the external files at injection time).
    // ---------------------------------------------------------------------------
    let _fs;
    function nodeFs() {
        if (_fs !== undefined) return _fs;
        _fs = null;
        try {
            if (typeof require === 'function') _fs = require('fs');
        } catch (e) {
            _fs = null;
        }
        return _fs;
    }

    function externalLocalesDir() {
        try {
            if (typeof process === 'undefined' || !process.platform) return null;
            if (typeof require !== 'function') return null;
            const os = require('os');
            const home = os.homedir();
            if (process.platform === 'win32') {
                return (process.env.APPDATA || (home + '/AppData/Roaming')) + '/Antigravity/locales';
            }
            if (process.platform === 'darwin') {
                return home + '/Library/Application Support/Antigravity/locales';
            }
            return home + '/.config/Antigravity/locales';
        } catch (e) {
            return null;
        }
    }

    let externalStamp = null;

    function applyExternalDicts(zh, pats) {
        const merged = {};
        for (const k in EMBEDDED_TRANSLATIONS) merged[k] = EMBEDDED_TRANSLATIONS[k];
        if (zh) for (const k in zh) merged[k] = zh[k];
        translations = merged;
        rawPatterns = (pats && pats.length) ? pats : EMBEDDED_PATTERNS;
        rebuildIndexes();
    }

    function tryLoadExternalDicts() {
        const fs = nodeFs();
        const dir = externalLocalesDir();
        if (!fs || !dir) return;
        try {
            let zh = null, pats = null, stamp = '';
            try {
                const p = dir + '/zh-CN.json';
                zh = JSON.parse(fs.readFileSync(p, 'utf8'));
                stamp += String(fs.statSync(p).mtimeMs) + '|';
            } catch (e) { /* missing or unreadable */ }
            try {
                const p = dir + '/patterns.json';
                pats = JSON.parse(fs.readFileSync(p, 'utf8'));
                stamp += String(fs.statSync(p).mtimeMs);
            } catch (e) { /* missing or unreadable */ }
            if (stamp !== externalStamp) {
                externalStamp = stamp;
                applyExternalDicts(zh, pats);
            }
        } catch (e) {
            // Corrupt external dictionaries must never take the client down.
        }
    }

    // ---------------------------------------------------------------------------
    // Translation core
    // ---------------------------------------------------------------------------
    const TRANSLATABLE_ATTRS = [
        'placeholder',
        'title',
        'aria-label',
        'aria-description',
        'aria-placeholder',
        'data-tooltip',
        'tooltip',
        'data-tip',
        'data-title',
        'data-placeholder',
        'alt'
    ];

    // Untranslated tracker. Persisting is debounced: writing the whole array to
    // localStorage on every new string is O(n^2) and floods storage with code
    // editor content on slower machines.
    const untranslatedSet = new Set();
    try {
        const existing = JSON.parse(localStorage.getItem('ag_untranslated') || '[]');
        existing.forEach(item => untranslatedSet.add(item));
    } catch (e) {}

    let persistTimer = null;
    function persistUntranslated() {
        if (persistTimer) {
            clearTimeout(persistTimer);
            persistTimer = null;
        }
        try {
            localStorage.setItem('ag_untranslated', JSON.stringify(Array.from(untranslatedSet)));
        } catch (e) {}
    }
    function schedulePersistUntranslated() {
        if (persistTimer) return;
        persistTimer = setTimeout(() => {
            persistTimer = null;
            persistUntranslated();
        }, 3000);
    }
    window.addEventListener('beforeunload', persistUntranslated);

    function recordUntranslated(str) {
        if (!str || str.length < 2 || str.length > 300) return;
        if (untranslatedSet.size >= 1000) return;
        if (/^[0-9\s:._\-/\+$,#&'"\[\]{}()\\<>=!*?|`@%]+$/.test(str)) return;
        if (/[一-鿿]/.test(str)) return;
        if (!untranslatedSet.has(str)) {
            untranslatedSet.add(str);
            schedulePersistUntranslated();
        }
    }

    function translateText(text) {
        if (currentLang === 'en') return null;
        if (!text) return null;
        const trimmed = text.trim();
        if (!trimmed) return null;

        // Skip if already contains Chinese
        if (/[一-鿿]/.test(trimmed)) return null;
        if (trimmed.length > 500) return null;

        // 1. Exact match
        if (translations[trimmed]) {
            return text.replace(trimmed, translations[trimmed]);
        }

        // 2. Case-insensitive match
        const lower = trimmed.toLowerCase();
        if (lowerTranslations[lower]) {
            return text.replace(trimmed, lowerTranslations[lower]);
        }

        // 3. Dynamic regex patterns
        for (const p of patterns) {
            if (p.regex.test(trimmed)) {
                const replaced = trimmed.replace(p.regex, p.replace);
                return text.replace(trimmed, replaced);
            }
        }

        // Record as untranslated
        recordUntranslated(trimmed);
        return null;
    }

    function translateElementAttrs(node) {
        if (!node || node.nodeType !== 1) return;
        for (const attr of TRANSLATABLE_ATTRS) {
            const val = node.getAttribute(attr);
            if (val) {
                const translated = translateText(val);
                if (translated !== null && val !== translated) {
                    node.setAttribute(attr, translated);
                }
            }
        }
    }

    // ---------------------------------------------------------------------------
    // Skip zones: code editors, preformatted blocks and anything editable must
    // never be rewritten - both to protect displayed code and to keep editor
    // content out of the untranslated-words capture.
    // ---------------------------------------------------------------------------
    function isSkipElement(el) {
        if (!el || el.nodeType !== 1) return false;
        const tag = el.tagName;
        if (tag === 'PRE' || tag === 'CODE' || tag === 'TEXTAREA') return true;
        if (el.isContentEditable) return true;
        const cls = el.classList;
        if (cls && (cls.contains('monaco-editor') || cls.contains('CodeMirror')
                 || cls.contains('cm-editor') || cls.contains('view-lines')
                 || cls.contains('xterm') || cls.contains('terminal'))) return true;
        return false;
    }

    function insideSkipZone(el) {
        let cur = el, depth = 0;
        while (cur && cur !== document.body && depth < 25) {
            if (isSkipElement(cur)) return true;
            cur = cur.parentElement || (cur.parentNode && cur.parentNode.host);
            depth++;
        }
        return false;
    }

    const observedRoots = new WeakSet();

    function skipSubtree(walker, node) {
        // Move the walker past `node`'s entire subtree in document order.
        walker.currentNode = node;
        let next = walker.nextSibling();
        while (next === null && walker.parentNode() !== null) {
            next = walker.nextSibling();
        }
        return next;
    }

    function translateDOM(root) {
        if (!root) return;

        if (root.nodeType === 1) {
            if (isSkipElement(root)) return;
        } else if (root.nodeType === 3 && insideSkipZone(root.parentElement)) {
            return;
        }

        // Handle Shadow DOM if present
        if (root.shadowRoot && !observedRoots.has(root.shadowRoot)) {
            observedRoots.add(root.shadowRoot);
            translateDOM(root.shadowRoot);
            observeSubtree(root.shadowRoot);
        }

        // Handle Text Node
        if (root.nodeType === 3) {
            const val = root.nodeValue;
            const translated = translateText(val);
            if (translated !== null && val !== translated) {
                root.nodeValue = translated;
            }
            return;
        }

        // Handle Element Node
        if (root.nodeType === 1) {
            translateElementAttrs(root);

            if (nodeIsInputButton(root)) {
                const val = root.value;
                const translated = translateText(val);
                if (translated !== null && val !== translated) {
                    root.value = translated;
                }
            }
        }

        // Walk DOM Subtree
        try {
            const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT);
            let node = walker.nextNode();
            while (node) {
                if (node.nodeType === 1 && isSkipElement(node)) {
                    node = skipSubtree(walker, node);
                    continue;
                }

                if (node.shadowRoot && !observedRoots.has(node.shadowRoot)) {
                    observedRoots.add(node.shadowRoot);
                    translateDOM(node.shadowRoot);
                    observeSubtree(node.shadowRoot);
                }

                if (node.nodeType === 3) {
                    const val = node.nodeValue;
                    const translated = translateText(val);
                    if (translated !== null && val !== translated) {
                        node.nodeValue = translated;
                    }
                } else if (node.nodeType === 1) {
                    translateElementAttrs(node);
                    if (nodeIsInputButton(node)) {
                        const val = node.value;
                        const translated = translateText(val);
                        if (translated !== null && val !== translated) {
                            node.value = translated;
                        }
                    }
                }
                node = walker.nextNode();
            }
        } catch (e) {}
    }

    function nodeIsInputButton(node) {
        return node.tagName === 'INPUT' && (node.type === 'button' || node.type === 'submit' || node.type === 'reset');
    }

    function observeSubtree(target) {
        if (!target) return;
        const obs = new MutationObserver((mutations) => {
            obs.disconnect();
            try {
                for (const mutation of mutations) {
                    if (mutation.type === 'childList') {
                        mutation.addedNodes.forEach(n => {
                            if (n.nodeType === 1 && isSkipElement(n)) return;
                            if (n.nodeType === 3 && insideSkipZone(n.parentElement)) return;
                            translateDOM(n);
                        });
                    } else if (mutation.type === 'characterData') {
                        const node = mutation.target;
                        if (!insideSkipZone(node.parentElement)) {
                            const val = node.nodeValue;
                            const translated = translateText(val);
                            if (translated !== null && val !== translated) {
                                node.nodeValue = translated;
                            }
                        }
                    }
                }
            } finally {
                obs.observe(target, { childList: true, subtree: true, characterData: true });
            }
        });
        obs.observe(target, { childList: true, subtree: true, characterData: true });
    }

    function startMainObserver() {
        if (!document.body) return;
        observeSubtree(document.body);
    }

    function startPeriodicScan() {
        setInterval(() => {
            if (document.body) {
                try { tryLoadExternalDicts(); } catch (e) {}
                try { injectLanguageSwitcher(); } catch (e) {}
                translateDOM(document.body);
            }
        }, 2000);
    }

    function injectLanguageSwitcher() {
        if (document.getElementById('antigravity-lang-switcher')) return;

        // Search for titlebar or menu container
        const menuItems = Array.from(document.querySelectorAll('*'));
        let targetEl = null;
        for (const el of menuItems) {
            if (el.childNodes.length === 1 && el.childNodes[0].nodeType === 3) {
                const text = el.textContent.trim();
                if (text === 'Window' || text === '窗口' || text === 'Help' || text === '帮助') {
                    targetEl = el;
                    break;
                }
            }
        }

        if (!targetEl && document.body) {
            // Fallback floating toggle if menu item not found
            const floatBtn = document.createElement('div');
            floatBtn.id = 'antigravity-lang-switcher';
            floatBtn.textContent = currentLang === 'zh' ? '中/EN' : 'EN/中';
            floatBtn.title = '点击切换语言 (Switch Language)';
            floatBtn.style.position = 'fixed';
            floatBtn.style.top = '6px';
            floatBtn.style.right = '140px';
            floatBtn.style.zIndex = '999999';
            floatBtn.style.padding = '2px 8px';
            floatBtn.style.fontSize = '11px';
            floatBtn.style.background = 'rgba(128,128,128,0.2)';
            floatBtn.style.border = '1px solid rgba(128,128,128,0.3)';
            floatBtn.style.borderRadius = '4px';
            floatBtn.style.cursor = 'pointer';
            floatBtn.style.userSelect = 'none';
            floatBtn.style.color = 'inherit';
            floatBtn.addEventListener('click', () => {
                const nextLang = currentLang === 'zh' ? 'en' : 'zh';
                localStorage.setItem('antigravity_lang', nextLang);
                location.reload();
            });
            document.body.appendChild(floatBtn);
            return;
        }

        if (targetEl && targetEl.parentNode) {
            const btn = document.createElement(targetEl.tagName || 'div');
            btn.className = targetEl.className;
            if (targetEl.getAttribute('style')) {
                btn.setAttribute('style', targetEl.getAttribute('style'));
            }
            btn.id = 'antigravity-lang-switcher';
            btn.textContent = currentLang === 'zh' ? 'EN' : '中文';
            btn.title = currentLang === 'zh' ? '点击切换为英文 (Switch to English)' : '点击切换为中文 (Switch to Chinese)';
            btn.style.cursor = 'pointer';
            btn.style.userSelect = 'none';
            btn.style.marginLeft = '8px';
            btn.style.marginRight = '8px';
            btn.style.padding = '0 8px';
            btn.style.display = 'inline-flex';
            btn.style.alignItems = 'center';
            btn.style.justifyContent = 'center';
            btn.style.fontWeight = '500';
            btn.style.opacity = '0.85';
            btn.style.transition = 'all 0.2s ease';

            btn.addEventListener('mouseenter', () => {
                btn.style.opacity = '1';
                btn.style.backgroundColor = 'rgba(255, 255, 255, 0.1)';
            });
            btn.addEventListener('mouseleave', () => {
                btn.style.opacity = '0.85';
                btn.style.backgroundColor = 'transparent';
            });
            btn.addEventListener('click', (e) => {
                e.preventDefault();
                e.stopPropagation();
                const nextLang = currentLang === 'zh' ? 'en' : 'zh';
                localStorage.setItem('antigravity_lang', nextLang);
                location.reload();
            });

            targetEl.parentNode.insertBefore(btn, targetEl.nextSibling);
        }
    }

    // Global shortcut Ctrl+Alt+L (macOS: Option+Cmd+L) to export untranslated text
    window.addEventListener('keydown', (e) => {
        const isL = (e.key === 'l' || e.key === 'L' || e.code === 'KeyL');
        const isModifier = e.altKey && (e.ctrlKey || e.metaKey);
        if (isModifier && isL) {
            persistUntranslated();
            const list = Array.from(untranslatedSet);
            const jsonStr = JSON.stringify(list, null, 2);
            if (navigator.clipboard && navigator.clipboard.writeText) {
                navigator.clipboard.writeText(jsonStr).then(() => {
                    showToast(`已复制 ${list.length} 条待翻译词汇到剪贴板！`);
                }).catch(() => {
                    showCopyOverlay(jsonStr, list.length);
                });
            } else {
                showCopyOverlay(jsonStr, list.length);
            }
        }
    });

    function showToast(msg) {
        const toast = document.createElement('div');
        toast.textContent = msg;
        toast.style.position = 'fixed';
        toast.style.bottom = '24px';
        toast.style.right = '24px';
        toast.style.background = '#1e8e3e';
        toast.style.color = '#ffffff';
        toast.style.padding = '10px 18px';
        toast.style.borderRadius = '8px';
        toast.style.boxShadow = '0 4px 12px rgba(0,0,0,0.3)';
        toast.style.zIndex = '999999';
        toast.style.fontSize = '14px';
        toast.style.fontWeight = '500';
        toast.style.transition = 'opacity 0.4s ease';
        document.body.appendChild(toast);
        setTimeout(() => {
            toast.style.opacity = '0';
            setTimeout(() => toast.remove(), 400);
        }, 3000);
    }

    function showCopyOverlay(text, count) {
        // Clipboard unavailable (e.g. non-secure context): surface the data in
        // a selectable box instead of only pointing at localStorage.
        const overlay = document.createElement('div');
        overlay.style.position = 'fixed';
        overlay.style.bottom = '24px';
        overlay.style.right = '24px';
        overlay.style.maxWidth = '420px';
        overlay.style.background = '#2d2f31';
        overlay.style.color = '#ffffff';
        overlay.style.padding = '12px';
        overlay.style.borderRadius = '8px';
        overlay.style.boxShadow = '0 4px 12px rgba(0,0,0,0.3)';
        overlay.style.zIndex = '999999';
        overlay.style.fontSize = '12px';
        overlay.style.display = 'flex';
        overlay.style.flexDirection = 'column';
        overlay.style.gap = '8px';

        const hint = document.createElement('div');
        hint.textContent = `剪贴板不可用：已捕获 ${count} 条词汇，请手动复制（Ctrl+C 后点击关闭）`;
        const box = document.createElement('textarea');
        box.value = text;
        box.style.width = '380px';
        box.style.height = '160px';
        box.style.fontSize = '11px';
        box.readOnly = true;
        const close = document.createElement('button');
        close.textContent = '关闭';
        close.style.alignSelf = 'flex-end';
        close.style.cursor = 'pointer';
        close.addEventListener('click', () => overlay.remove());
        overlay.appendChild(hint);
        overlay.appendChild(box);
        overlay.appendChild(close);
        document.body.appendChild(overlay);
        box.focus();
        box.select();
    }

    // Initialize
    function init() {
        try {
            tryLoadExternalDicts();
            if (currentLang === 'en') {
                // English mode: keep only the language switcher alive; no DOM
                // scanning, no observers, no dictionary matching.
                injectLanguageSwitcher();
                return;
            }
            injectLanguageSwitcher();
            if (document.body) {
                translateDOM(document.body);
                startMainObserver();
                startPeriodicScan();
            }
        } catch (e) {
            console.error('[AG-ZH] Init error:', e);
        }
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
